Mention that yarn is not supported in install
aws-amplify/docs pull request #2342
Opened 2020-09-01 17:12 UTC by pickfire

We shouldn't let users waste their precious time figuring out why stuff
just does not work if they happened to install it through yarn like me.

*Issue #, if available:* -

*Description of changes:* Yarn is not supported, mention that, don't waste others time

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-01 17:28 UTC, sw-yx commented
i dont understand. i use yarn myself. can you please open an issue explaining what errors you faced?

2020-09-02 00:14 UTC, pickfire commented
@sw-yx I have multiple issues, first I see https://github.com/aws-amplify/amplify-cli/issues/4890#issuecomment-663315972 when `amplify configure` and https://github.com/aws-amplify/amplify-cli/issues/4043#issue-605022654 when `amplify init`.

2020-09-02 08:57 UTC, sw-yx requested changes
would change this to "local installs are not supported" instead of "yarn is not supported"

2020-09-02 14:30 UTC, pickfire commented
@sw-yx It is true that local install is not supported but global yarn install is broken too, which is why `npx` does not work too.

2020-10-04 00:08 UTC, pickfire commented
Ping

2020-10-16 19:58 UTC, mauerbac commented
@renebrandel , can you review please?

2020-11-16 06:50 UTC, pickfire commented
Ping

2020-11-16 14:10 UTC, mauerbac commented
Will ping @renebrandel internally

2020-11-16 16:06 UTC, renebrandel commented
Hi @pickfire - what's the yarn command that you're running that has the issue? `npx` is not working because the package name was reserved by a 3rd party unaffiliated with AWS https://www.npmjs.com/package/amplify 

You are correct. Local npm install is not working. Happy to approve the PR modified to the local npm installs first. 

Let me get to the bottom of the yarn installation issue separately.

2020-11-16 16:19 UTC, pickfire commented
> Hi @pickfire - what's the yarn command that you're running that has the issue? npx is not working because the package name was reserved by a 3rd party unaffiliated with AWS https://www.npmjs.com/package/amplify

I don't fully recall but I probably installed it with `sudo yarn global add amplify`. Not sure if this is related but I am using Arch, I don't recall which yarn version I was using but should be the latest at that time, I used nodejs latest lts (maybe 12/14 at that time?), it's been quite long and I don't recall all the parts already.

2020-11-17 22:34 UTC, renebrandel commented
Yeah. That's the wrong yarn command. Yarn leverages the same set of package names as npm. Therefore for yarn, you'll need to run `yarn global add @aws-amplify/cli`.

2020-11-18 03:09 UTC, pickfire commented
I don't recall but maybe I used `yarn global add @aws-amplify/cli`.

2020-12-20 10:44 UTC, pickfire commented on docs/cli/start/install.md
> +* [Install Node.js®](https://nodejs.org/en/download/) and [NPM](https://www.npmjs.com/get-npm) if they are not already on your machine. (Both [Yarn](https://yarnpkg.com/) and local NPM install is not
Where is this?

> Because we're installing the Amplify CLI globally, you might need to run the command above with sudo.

2021-01-25 02:18 UTC, pickfire commented
I will just close this since I am not using amplify anymore.

2021-01-25 02:18 UTC, closed without merging