first pass at adding build/packaging details for Python functions
aws-amplify/docs pull request #2479
Opened 2020-09-30 23:45 UTC by jazwiecki

*Issue #, if available:* #2478

*Description of changes:* Adds barebones documentation of build & package steps for Python functions, specifically around packaging dependencies.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-01 20:10 UTC, renebrandel requested changes

2020-10-01 20:10 UTC, renebrandel commented on docs/cli/function/build-options.md
> +## Python
I'd move the Python section below the NodeJS section.

2020-10-01 20:10 UTC, renebrandel commented on docs/cli/function/build-options.md
> +**There are no existing build options for Python functions**
Remove the bold lettering here and move it and collapse it into the next paragraph as the first sentence.

2020-10-01 20:10 UTC, renebrandel commented on docs/cli/function/build-options.md
> +The process of building and packaging Python functions is in line with Amazon's [existing documentation](https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-venv) for manu
Move "Amplify will run..." into its own paragraph.

2020-10-01 20:10 UTC, renebrandel commented on docs/cli/function/build-options.md
> +The process of building and packaging Python functions is in line with Amazon's [existing documentation](https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-venv) for manu
Remove "comma" from "...directory during builds, using either..."

2020-10-01 20:10 UTC, renebrandel commented on docs/cli/function/build-options.md
> +This means that the contents of the Python build can include local development dependencies (e.g. for testing) in addition to those necessary for your function to run. This also means that packages i
Shorten for readability. Remove "This means..." from both sentences. "The contents of..." and "Packages installed as..."

2020-10-01 20:10 UTC, renebrandel commented on docs/cli/function/build-options.md
> +This means that the contents of the Python build can include local development dependencies (e.g. for testing) in addition to those necessary for your function to run. This also means that packages i
Shorten for clarity: Remove "properly". "... will not be packaged" is also accurate and shortened.

2020-10-01 20:10 UTC, renebrandel commented on docs/cli/function/build-options.md
> +This means that the contents of the Python build can include local development dependencies (e.g. for testing) in addition to those necessary for your function to run. This also means that packages i
Shorten for readability: "as their only representation in the `site-packages` directory is an `.egg-link` file pointing to the local, editable code of the dependency" --> "as they are represented as an `.egg-link` file pointing to the local, editable code of the dependency."

2020-10-12 22:53 UTC, renebrandel approved these changes

2020-10-22 15:37 UTC, mauerbac commented
@jazwiecki , can you fix this merge conflict?

2020-10-22 16:25 UTC, jazwiecki commented
@mauerbac yep, think I got it.

2020-10-23 16:18 UTC, mauerbac commented
can we get a review @aws-amplify/amplify-cli

2020-11-27 15:38 UTC, jazwiecki commented
AFAIK this is just waiting on a review from the CLI team. Not urgent but it was helpful for me to figure this stuff out, might be useful for other people to know how the CLI packages Python lambdas without having to do their own research.

2020-12-03 19:10 UTC, edwardfoyle approved these changes

2021-01-04 03:49 UTC, jazwiecki commented
Figured out how to fix the spellcheck failure, sorry about that!

2021-01-26 19:13 UTC, ericclemmons commented
Thanks for the updates! Merging this in...

2021-01-26 19:13 UTC, merged