docs: update feature flag to include addMissingOwerFields
aws-amplify/docs pull request #2523
Opened 2020-10-09 20:26 UTC by yuth

update feature flag to include graphQLTransformer.addMissingOwnerFields

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-19 21:15 UTC, renebrandel approved these changes

2020-10-19 21:15 UTC, renebrandel requested changes

2020-10-19 21:15 UTC, renebrandel commented on client/src/amplify-ui/cli-feature-flag/feature-flags.json
> +            "description": "don't insert the owner field automatically",
Doesnt*

2020-10-19 21:15 UTC, renebrandel commented on client/src/amplify-ui/cli-feature-flag/feature-flags.json
> +            "description": "inserts the owner field from auth rules when its missing in type",
Capitalize Inserts

2020-10-19 21:26 UTC, renebrandel approved these changes

2020-10-19 21:31 UTC, attilah approved these changes
one nit comment

2020-10-19 21:31 UTC, attilah commented on client/src/amplify-ui/cli-feature-flag/feature-flags.json
> +        "description": "Automatically add owner field to when owner fields are not in the type",
the 'to' seems to be an extra, without it: "Automatically add owner field when owner fields are not in the type"

2020-10-20 01:16 UTC, attilah approved these changes

2020-10-20 16:28 UTC, merged