Update getting-started.md with CORS Policy
aws-amplify/docs pull request #2909
Opened 2021-02-03 20:36 UTC by Ochaun

S3 bucket CORS Policies require JSON instead of XML now.

*Issue #, if available:*
- https://github.com/aws-amplify/amplify-js/issues/169

*Description of changes:*
- converted the old xml CORS policy to JSON. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-02-03 23:51 UTC, amhinson requested changes
Thanks for this update! I just have one comment/suggestion regarding the configuration.

2021-02-03 23:51 UTC, amhinson commented on docs/lib/storage/fragments/js/getting-started.md
> +}
This looks similar, but slightly different than what is automatically created with the Amplify CLI. What do you think of just using exactly the same configuration here? I just pulled this from a sample app I created.

```suggestion
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "x-amz-server-side-encryption",
            "x-amz-request-id",
            "x-amz-id-2",
            "ETag"
        ],
        "MaxAgeSeconds": 3000
    }
]
```

2021-02-08 22:05 UTC, Ochaun commented
Fine by me.

2021-02-08 22:07 UTC, amhinson approved these changes
Thanks! LGTM 👍

2021-02-08 22:08 UTC, merged