Update integrate.md
aws-amplify/docs pull request #3012
Opened 2021-03-04 16:11 UTC by evcodes

*Issue #, if available:*

*Description of changes:*
When working on Android Getting Started project the code snippet for saving the items to Amplify DataStore the code block for Kotlin has

try {
            Amplify.DataStore.save(item)
            Log.i("Tutorial", "Saved item: ${item.name}")
        } catch (error: AmplifyException) {
            Log.e("Tutorial", "Could not save item to DataStore", error)
        )

However, this does not allow me to save items to DataStore because the Amplify.DataStore.save() expects three parameters:
- an item
- onItemSaved
- onFailureToSave

the function in the documentation provided does not have the correct parmeters in the try catch block. Instead, I copied the Java version of this code into Android and had it automatically change to Kotlin and got this:

 Amplify.DataStore.save(
    item,
    { success: DataStoreItemChange<Todo> -> Log.i("Tutorial", "Saved item: " + success.item().name) },
    { error: DataStoreException? -> Log.e("Tutorial", "Could not save item to DataStore", error) }
)

We could potentially wrap this in a try catch block like this:

```
        try {
            Amplify.DataStore.save(
                    item,
                    { success: DataStoreItemChange<Todo> -> Log.i("Tutorial", "Saved item: " + success.item().name) },
                    { error: DataStoreException? -> Log.e("Tutorial", "Could not save item to DataStore", error) }
            )
        } catch (error: AmplifyException) {
            Log.e("Tutorial", "Could not save item to DataStore", error)
        }
```

This fix allowed me to save items to DataStore in Android.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-04 16:23 UTC, evcodes commented
> ```
> implementation 'com.amplifyframework:core-kotlin:0.1.1'
> ```

Great, I will try this and get back to you. I can write those changes to the getting started guide too.

2021-03-04 16:29 UTC, richardmcclellan commented
> I can write those changes to the getting started guide too.

Thank you, I'd appreciate that!

2021-03-04 16:45 UTC, jamesonwilliams reviewed
Hi @evcodes! Please see: https://docs.amplify.aws/lib/project-setup/coroutines/q/platform/android

The Kotlin code snippets have recently been updated with improved language support.

2021-03-04 23:36 UTC, jamesonwilliams requested changes
I've done an update to the Getting Started guide to move all the examples uniformly back to the callback approach. Am going through and updating the category documentation to include a disambiguation between the callback apis and the coroutines APIs, as well.

It may be appropriate to update the Getting Started guide itself to use the Coroutines, but the Coroutines library is still at 0.1.1. We should wait for it to stabilize to 1.x.

2021-03-18 17:04 UTC, jamesonwilliams commented
Will close for now - let's revisit using `core-kotlin` in the Getting Started guide a little later.

2021-03-18 17:04 UTC, closed without merging