Update integrate.md
aws-amplify/docs pull request #3036
Opened 2021-03-08 16:30 UTC by GMerakis

Include an explanation on why the code won't compile

*Issue #, if available:*
#3035

*Description of changes:*
There are multiple questions regarding this issue, few solutions.
The issue can actually be solved by following the tutorial but this was not called out in the doc

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-18 17:00 UTC, jamesonwilliams commented on docs/start/getting-started/fragments/flutter/integrate.md
> +**Note**: the code won't compile until after you have finished <b>*'Connect to the cloud'*</b> section of the tutorial.
`<amplify-callout>` perhaps?

2021-03-18 17:00 UTC, jamesonwilliams approved these changes
`<amplify-callout>` perhaps?

2021-03-19 00:04 UTC, GMerakis commented
> `<amplify-callout>` perhaps?

done

2021-03-19 14:34 UTC, palpatim commented
@haverchuck Can you or one of the Flutter team take a look at this & merge it in if it meets with your approval?

2021-04-07 16:42 UTC, drochetti requested changes

2021-04-07 16:42 UTC, drochetti commented on docs/start/getting-started/fragments/flutter/integrate.md
> +<amplify-callout> The code won't compile until after you have finished <b>*'Connect to the cloud'*</b> section of the tutorial. </amplify-callout>
in order to render markdown correctly, `amplify-callout` requires you to skip a line after the opening tag and before closing it. Also, plain markdown is preferred over `<b>`.

That being said, I think a better fit for it is to actually link to the section of the tutorial you mentioned, here's my suggestion.

```suggestion
<amplify-callout>

The code won't compile until after you have finished [Connect to the cloud](~/start/getting-started/integrate.md) section of the tutorial.

</amplify-callout> 
```

2021-07-01 21:01 UTC, closed without merging