add permission boundary docs
aws-amplify/docs pull request #3157
Opened 2021-04-20 23:53 UTC by edwardfoyle

*Issue #, if available:*

*Description of changes:*
Add docs for upcoming Permission Boundary feature

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-22 03:14 UTC, medelman17 requested changes

2021-04-22 03:14 UTC, medelman17 commented on docs/cli/usage/permission-boundary.md
> +
I think we need more context/introduction, here, re: what this feature does as a general matter / why we added it / and why a user might find it useful. In other words, can we include the user story?

2021-04-22 03:14 UTC, medelman17 commented on docs/cli/usage/permission-boundary.md
> +To set the maximum permissions that can be granted to IAM Roles created by Amplify CLI, a [Permission Boundary](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html) can b
Could we include a bit of background regarding what Amplify does behind the scenes with respect to creating IAM roles? To the extent that we document that elsewhere, let's link to that resource.

2021-04-22 03:14 UTC, medelman17 commented on docs/cli/usage/permission-boundary.md
> +Amplify CLI does not create an IAM Policy to use as a Permission Boundary. This must be configured outside of the project (typically as part of an AWS Org rule or other enterprise rule).
Include steps for creating the Permission Boundary via the console, including an example permission boundary. This should also highlight how/where to find the ARN.

2021-04-22 03:14 UTC, medelman17 commented on docs/cli/usage/permission-boundary.md
> +Rerun the steps above to change the Permission Boundary at any time.
Please expand. For example, when do I need to run the above steps? Anytime I change the Permission Boundary Role? Or only if I create a new one? Etc.

2021-06-16 01:31 UTC, closed without merging

2021-06-16 01:32 UTC, renebrandel commented
Closing this as I made a mistake and created a new PR with all the updates in #3319