remove stale code block for API env endpoints
aws-amplify/docs pull request #3281
Opened 2021-06-01 21:18 UTC by edwardfoyle

_Issue #, if available:_
https://github.com/aws-amplify/amplify-cli/issues/7404

_Description of changes:_
Remove code block that shows an incorrect example of how multi-env REST APIs are handled in the CLI

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-02 00:24 UTC, kierans commented
@edwardfoyle Thanks for this fix. I suggest mentioning that the different deployments will have different URLs. This is important IMHO because if you've used API Gateway in the past then you know about stages.

2021-06-04 00:52 UTC, medelman17 requested changes
@edwardfoyle -- I dug the explanation you provided in the originating issue re: how and why Amplify will create separate APIs per environment (rather than separate stages within the same API). I would consider adding something similar, here. E.g., 

"Note: Because individual Amplify environments can exist in different accounts (e.g., "Dev" environment in "Dev" account; "Prod" environment in "Prod" account), Amplify will create separate API gateway instances for each environment."

2021-07-09 08:05 UTC, kierans commented
@edwardfoyle Is there any chance you could finish this off?

2021-11-10 21:22 UTC, siegerts approved these changes

2021-11-10 21:44 UTC, jhockett approved these changes

2021-11-11 14:33 UTC, merged