fix(cli/auth): correct multi-auth example outputs
aws-amplify/docs pull request #3283
Opened 2021-06-03 19:09 UTC by josefaidt

_Issue #, if available:_

https://github.com/aws-amplify/amplify-cli/issues/6953

_Description of changes:_

Corrects example outputs based on the example schema, where owner ID should not populate as an editor when not also specifying `create` in the "editors" rule's operations.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-05 03:00 UTC, medelman17 requested changes
Revise use of informal language / second person plural.

2021-06-05 19:46 UTC, josefaidt commented
Which piece are you referring to? These changes are mostly to correct the output

2021-06-11 14:28 UTC, josefaidt commented
@medelman17 which piece are you referring to with the language revision suggestion?

2021-06-21 16:18 UTC, edwardfoyle approved these changes

2021-07-28 15:42 UTC, medelman17 approved these changes

2021-07-28 15:43 UTC, merged