docs(overview): define which section of .gitignore is managed by amplify
aws-amplify/docs pull request #3330
Opened 2021-06-21 20:15 UTC by johnpc

_Issue #, if available:_

https://github.com/aws-amplify/amplify-cli/issues/

_Description of changes:_

This pull request adds documentation for the fact that Amplify CLI manages a section of each project's .gitignore file which should not be touched by the application owner.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-23 22:18 UTC, josefaidt reviewed
will the begin marker still contain the hash?

```
#amplify-do-not-edit-begin
```

2021-08-12 17:17 UTC, josefaidt requested changes

2021-08-12 17:17 UTC, josefaidt commented on docs/cli/teams/overview.md
> +**Note:** When you initialize a project using the Amplify CLI, it appends (if a gitignore file exists at the root of the project) or creates one for you (if a gitignore file doesn't exist at the root
```suggestion
**Note:** When you initialize a project using the Amplify CLI, it appends (if a gitignore file exists at the root of the project) or creates one for you (if a gitignore file doesn't exist at the root of your project), with a list of recommended files to check in from the Amplify CLI generated list of files, into your Git repository. Amplify CLI will continue to manage the section of your .gitignore between the `#amplify-do-not-edit-begin` and `#amplify-do-not-edit-end` pragmas.
```

2021-08-13 18:22 UTC, edwardfoyle approved these changes

2021-08-13 18:30 UTC, josefaidt approved these changes

2021-08-13 18:35 UTC, merged