Amplify Mock: Add note about JDK issues on Apple Silicon
aws-amplify/docs pull request #3409
Opened 2021-07-20 22:40 UTC by danabrams

_Issue #, if available:_ [7411](https://github.com/aws-amplify/amplify-cli/issues/7411)

_Description of changes:_
Added a note describing the fix for this issue on Apple Silicon (M1) Macs

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-21 20:44 UTC, josefaidt requested changes
Hey @danabrams thanks again for taking this on! I've added a few comments for adjustments

2021-07-21 20:44 UTC, josefaidt commented on docs/cli/usage/mock.md
> +> Currently, on Apple Silicon Macs, Amplify sometimes fails to start mocks when using certain JDK versions built for Arm processors.
```suggestion
> **NOTE:** Currently, on Apple Silicon Macs, Amplify sometimes fails to start mocks when using certain JDK versions built for ARM processors. 
```

2021-07-21 20:44 UTC, josefaidt commented on docs/cli/usage/mock.md
> +> If you encounter [this issue](https://github.com/aws-amplify/amplify-cli/issues/7411), please try using the official openJDK 16.0.1 from the Java website: [JDK Download](https://github.com/aws-ampl
```suggestion
> If you encounter [this issue](https://github.com/aws-amplify/amplify-cli/issues/7411), please try using the official openJDK 16.0.1 from the Java website: [JDK Download](https://jdk.java.net/16/)
```

2021-07-21 20:44 UTC, josefaidt commented on docs/cli/usage/mock.md
> +> Currently, on Apple Silicon Macs, Amplify sometimes fails to start mocks when using certain JDK versions built for Arm processors.
Adding `NOTE` will adhere to other instances of blockquotes with notes

2021-07-21 20:44 UTC, josefaidt commented on docs/cli/usage/mock.md
> +> If you encounter [this issue](https://github.com/aws-amplify/amplify-cli/issues/7411), please try using the official openJDK 16.0.1 from the Java website: [JDK Download](https://github.com/aws-ampl
this URL wasn't working for me, added the Java 16 page in its place

2021-07-21 20:47 UTC, danabrams commented
> Hey @danabrams thanks again for taking this on! I've added a few comments for adjustments

Both suggestions are fair enough. I've committed them.

2021-07-21 20:48 UTC, josefaidt approved these changes

2021-09-14 15:21 UTC, ammarkarachi approved these changes

2021-09-22 18:48 UTC, merged