Update getting started Android
aws-amplify/docs pull request #3414
Opened 2021-07-21 22:45 UTC by dengdan154

_Issue #, if available:_

_Description of changes:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-26 23:07 UTC, poojamat approved these changes

2021-07-27 04:03 UTC, div5yesh requested changes

2021-08-03 22:21 UTC, div5yesh approved these changes
Ship it 🚢

2021-08-03 22:21 UTC, div5yesh commented on docs/start/getting-started/fragments/android/add-api.md
> +       Log.i("Tutorial", "Initialized Amplify");
Indentation fixes.

```suggestion
      Log.i("Tutorial", "Initialized Amplify");
```

2021-08-03 22:21 UTC, div5yesh commented on docs/start/getting-started/fragments/android/add-api.md
> +   Amplify.DataStore.observe(Todo.class,
```suggestion
  Amplify.DataStore.observe(Todo.class,
```

2021-08-03 22:21 UTC, div5yesh commented on docs/start/getting-started/fragments/android/add-api.md
> +   Amplify.DataStore.observe(Todo::class.java,
```suggestion
  Amplify.DataStore.observe(Todo::class.java,
```

2021-08-03 22:40 UTC, merged