Changed AWS Lambda IAM Authorization Example
aws-amplify/docs pull request #3760
Opened 2021-11-10 20:37 UTC by renegoretzka

_Issue #3623_

_Description of changes:_
Changed the part of the AWS Lambda function IAM Authorization to a simple, lightweight, and easy to understand.
This follows more like the API.graphql() method from aws-amplify/js approach.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-23 17:33 UTC, evcodes commented on src/fragments/lib/graphqlapi/graphql-from-node.mdx
> +Next, you need to install two npm packages for your AWS Lambda function. To do so, open your terminal in the `amplify/backend/function/<YOUR_FUNCTION_NAME>/src` directory in your newly created AWS La
Next, you need to install two npm packages for your AWS Lambda function. To do so, open your terminal in the `amplify/backend/function/<YOUR_FUNCTION_NAME>/src` directory in your newly created AWS Lambda function and run the command `npm install appsync-client graphql-tag`. Once the packages are installed, add this your ```index.js```:

2021-11-23 17:37 UTC, evcodes commented on src/fragments/lib/graphqlapi/graphql-from-node.mdx
> +Finally you can define the GraphQL operation you're running, in this case the `createTodo` mutation, in a separate `graphql.js` file:
You can also define which GraphQL operation you're running. In this example, we are going to be creating a `createTodo` mutation within a separate `graphql.js` file.

2021-11-23 17:39 UTC, evcodes requested changes
Small grammatical nits but LGTM other than that. This dramatically simplifies Lambda authorizers and is the right thing to do from a security perspective.

2021-11-24 10:50 UTC, renegoretzka commented
Thank you @evcodes! I applied the suggested changes!

2022-02-21 23:43 UTC, sachscode reviewed
LGTM, just a few comments

2022-02-21 23:43 UTC, sachscode commented on src/fragments/lib/graphqlapi/graphql-from-node.mdx
> +    console.log('Something went wrong in the handler:', error);
can we use console.error here ?

2022-02-21 23:43 UTC, sachscode commented on src/fragments/lib/graphqlapi/graphql-from-node.mdx
> +const { createTodo } = require('./graphql.js');
```suggestion
const { createTodo } = require('./graphql.js'); /* GraphQL mutation */
```

2022-02-21 23:43 UTC, sachscode commented on src/fragments/lib/graphqlapi/graphql-from-node.mdx
> +const gql = require('graphql-tag');
```suggestion
const gql = require('graphql-tag'); /* To parse GraphQL strings into GraphQL AST */
```

2022-03-22 19:48 UTC, mauerbac commented
hey @renegoretzka - you able to finish this up?

2022-03-22 19:51 UTC, renegoretzka commented
Yeah, I will take care of it. Thanks for the reminder!

2022-11-09 21:20 UTC, katiegoines approved these changes

2022-11-09 21:24 UTC, josefaidt commented
Hey @renegoretzka :wave: sorry for the delay here, and quite honestly I updated this page not too, too long ago to use node-fetch and aws-sdk v3. Can you take a look at the merge conflicts and see how this change resonates with the updated doc? https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/#iam-authorization

2022-11-15 17:41 UTC, renegoretzka commented
Hey @josefaidt 👋  maybe we can drop this PR in favor of the solution you have provided :)

2022-11-16 18:01 UTC, katiegoines commented
@renegoretzka - Closing this PR per your comment. Thank you!

2022-11-16 18:01 UTC, closed without merging