Added Angular & Ionic data binding examples
aws-amplify/docs pull request #3763
Opened 2021-11-12 15:03 UTC by Jaykingamez

_Issue #, if available:_
#3243 
Images not shown if `img-key="{{file.key}}"` instead of `imgKey="{{file.key}}"`. Issue might have been transferred to amplify-js, but the problem still has not been remedied. In fact, an error is now thrown if `img-key="{{file.key}}"` is done in Anglar. 

_Description of changes:_
Add examples of data binding the  "img-key" attribute in Angular and Ionic

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-31 00:56 UTC, Milan-Shah approved these changes

2022-01-31 17:48 UTC, wlee221 commented on src/fragments/ui/storage/web/s3-image.mdx
> +<amplify-s3-image imgKey="{{filename}}"></amplify-s3-image>
Looks good, though I think data binding makes is more idiomatic here than interpolation:

```suggestion
<amplify-s3-image [imgKey]="filename"></amplify-s3-image>
```

2022-01-31 17:49 UTC, wlee221 commented on src/fragments/ui/storage/web/s3-image.mdx
> +<amplify-s3-image imgKey="{{filename}}"></amplify-s3-image>
Same suggestion:

```suggestion
<amplify-s3-image [imgKey]="{{filename}}"></amplify-s3-image>
```

2022-01-31 17:50 UTC, wlee221 requested changes
Thanks @Jaykingamez -- looks good, just one suggestion!

2022-04-04 19:06 UTC, offlineprogrammer approved these changes

2022-04-04 20:11 UTC, merged