Add platform independent sample script for headless init
aws-amplify/docs pull request #3895
Opened 2021-12-26 09:54 UTC by sytolk

_Issue #, if available:_ https://github.com/aws-amplify/amplify-cli/issues/9065

_Description of changes:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-04 17:19 UTC, josefaidt requested changes
Hey @sytolk thanks for raising this! While I think it is a great idea to write a platform-agnostic headless CLI script to initialize a project, I feel there is missing context here regarding `amplify.json` as the contents appear to be `amplify/.config/project-info.json`. Is this a sample to initialize an existing project or programmatically initialize a new project?

2022-05-04 18:12 UTC, sytolk commented
@josefaidt this script is the same like this: 
https://github.com/aws-amplify/docs/blob/main/src/pages/cli/usage/headless.mdx#headless-category-payloads
but for the init there is only bash script now: 
https://github.com/aws-amplify/docs/blob/main/src/pages/cli/usage/headless.mdx#sample-script
where is `amplify/.config/project-info.json` in this bash script now ?? amplify.json is the same like in bash script.. simple I not understand you question :)

2022-11-09 19:44 UTC, josefaidt commented
Hey @sytolk :wave: apologies for the delay here!!! As mentioned I do think the platform-agnostic script is a great addition, however I would prefer not introducing a third party dependency (`shelljs`), and is it possible to include the JSON blob as a string in the script rather than having a separate file? If not, can you rename the `amplify.json` sample name something like `amplify-headless-init-payload.json`?

2022-11-10 07:15 UTC, sytolk commented
Hi, @josefaidt I have renamed JSON file to amplify-headless-init-payload.json. In this doc `shelljs` is here only to be clear for developers that it's need to execute this command line. They will choose the command line execution library `execa` `shelljs` or simple node `child_process`. But if this third party dependency bothers you feels free to replace it.
_is it possible to include the JSON blob as a string_ - yes it's possible but I think this will be very bad design (this can be done with webpack build and.. simple let the developers choose this too). This is documentation only and needs to have only samples here :)

2022-11-11 20:31 UTC, josefaidt commented on src/pages/cli/usage/headless.mdx
> +}
```suggestion
{
  "amplify": {
    "projectName": "headlessProjectName",
    "envName": "myenvname",
    "defaultEditor": "code"
  },
  "frontend": {
    "frontend": "javascript",
    "framework": "react",
    "config": {
      "SourceDir": "src",
      "DistributionDir": "build",
      "BuildCommand": "npm run-script build",
      "StartCommand": "npm run-script start"
    }
  },
  "providers": {
    "awscloudformation": {
      "configLevel": "project",
      "useProfile": false,
      "profileName": "default"
    }
  }
}

```

2022-11-11 20:32 UTC, josefaidt commented on src/pages/cli/usage/headless.mdx
> +}
```suggestion
const shell = require('shelljs');
const amplify = require('./amplify-headless-init-payload.json');
const cmd =
  'amplify init --amplify "' +
  JSON.stringify(amplify.amplify).replaceAll('"', '\\"') +
  '" --frontend "' +
  JSON.stringify(amplify.frontend).replaceAll('"', '\\"') +
  '" --providers "' +
  JSON.stringify(amplify.providers).replaceAll('"', '\\"') +
  '" --yes';
  
if (shell.exec(cmd).code !== 0) {
  shell.echo('Error amplify init');
  shell.exit(1);
}
```

2022-11-11 20:33 UTC, josefaidt commented
Hey @sytolk thanks for the clarification and for the adjustment! I've left a small formatting suggestion and I think we'll be good to go!

2022-11-16 18:03 UTC, katiegoines submitted a review, later dismissed
lgtm!

2022-11-17 00:16 UTC, josefaidt approved these changes
LGTM, thank you @sytolk !! 🙏

2023-03-15 20:54 UTC, kuhlmanp approved these changes

2023-03-17 17:57 UTC, katiegoines approved these changes

2023-03-23 17:59 UTC, kuhlmanp approved these changes

2023-03-23 18:23 UTC, josefaidt approved these changes

2023-03-27 18:31 UTC, josefaidt submitted a review, later dismissed

2023-03-27 18:38 UTC, kuhlmanp approved these changes

2023-03-30 19:11 UTC, timngyn approved these changes

2023-03-30 20:52 UTC, josefaidt approved these changes

2023-03-30 20:53 UTC, merged