Updated Searchable docs with geo query instructions
aws-amplify/docs pull request #3944
Opened 2022-01-17 21:53 UTC by Rafcin

_Issue #, if available:_

The docs used to have info on how to set up `geo_point` queries with Elasticsearch.

_Description of changes:_

I added new documentation under searchable on how to create a custom resolver using the new method.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-18 16:34 UTC, offlineprogrammer approved these changes

2022-05-04 17:32 UTC, josefaidt commented on src/pages/cli/graphql/search-and-result-aggregations.mdx
> +Creating a geo query is straightforward. The first step is to create a custom resolver. For more information on creating custom resolvers check [here](https://docs.amplify.aws/cli/graphql/custom-busi
```suggestion
Creating a geo query is straightforward. The first step is to [create a custom resolver](https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver).
```

2022-05-04 17:33 UTC, josefaidt commented on src/pages/cli/graphql/search-and-result-aggregations.mdx
> +Before you create the templates, make sure to create a location field on your model, and properly map the `geo_point` type to the location field.
```suggestion
Before you create the templates make sure to create a location field on your model, and properly map the `geo_point` type to the location field. 
```

2022-05-04 17:36 UTC, josefaidt commented on src/pages/cli/graphql/search-and-result-aggregations.mdx
> +```ts
```suggestion
```text
```

2022-05-04 17:37 UTC, josefaidt commented on src/pages/cli/graphql/search-and-result-aggregations.mdx
> +```ts
```suggestion
```vtl
```

2022-05-04 17:41 UTC, josefaidt commented on src/pages/cli/graphql/search-and-result-aggregations.mdx
> +```ts
```suggestion
```vtl
```

2022-05-04 17:42 UTC, josefaidt requested changes
Hey @Rafcin :wave: thank you for contributing! I think this is great to include, and have requested a few small changes 🙂

2022-05-05 21:25 UTC, josefaidt approved these changes

2022-05-05 21:25 UTC, josefaidt commented
cc @renebrandel for visibility/thoughts

2022-11-09 19:41 UTC, josefaidt commented
bump @renebrandel and @swaminator for visibility. perhaps @AaronZyLee for searchable input

2024-01-03 20:20 UTC, hbuchel commented
Closing this PR due to its age and the docs site has since been refactored. Please feel free to update with latest and re-open if you feel it is still relevant, thanks.

2024-01-03 20:20 UTC, closed without merging