chore(geo): add escape hatch link to geo getting started
aws-amplify/docs pull request #4099
Opened 2022-03-03 18:10 UTC by thaddmt

_Issue #, if available:_

_Description of changes:_
- Add link to escape hatch on geo getting started per request from @hdworld11 

![Screen Shot 2022-03-03 at 10 05 51 AM](https://user-images.githubusercontent.com/68032955/156625803-02131099-e245-4b43-b93f-b077b4207197.png)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-03 22:40 UTC, offlineprogrammer approved these changes

2022-03-07 18:49 UTC, hdworld11 requested changes

2022-03-07 19:33 UTC, TreTuna commented on src/fragments/lib/geo/js/getting-started.mdx
I feel the want to combine them into one, but now they feel like they run together. Perhaps a different separation, like bullets? @hdworld11?

```suggestion
**Notes:** 
- If you want to use existing Amazon Location Service resources [follow this guide](/lib/geo/existing-resources) instead.
- If you want to use Amazon Location Service APIs not directly supported by Geo, use the [escape hatch](/lib/geo/escapehatch) to access the Amazon Location Service SDK.

```

2022-03-08 14:43 UTC, hdworld11 approved these changes

2022-03-08 16:18 UTC, Amplifiyer approved these changes

2022-03-08 16:57 UTC, merged