Update logger.mdx file, adding CloudWatch setup
aws-amplify/docs pull request #4246
Opened 2022-04-24 21:32 UTC by ktmdan

_Issue #, if available:_
None

_Description of changes:_
Add to the end of logger.mdx file
Setup for using AWSCloudWatchProvider including roles.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-09 18:46 UTC, josefaidt commented
Hey @ktmdan :wave: apologies for the delay here!! Can you describe the use case for this solution in more detail?

2022-12-09 19:30 UTC, ktmdan commented
This PR describes how to setup a website to log to CloudWatch using the Amplify logger.

2022-12-09 20:45 UTC, chrisbonifacio commented
Hi @ktmdan, thanks for the quick response. We discussed this internally and agree that this example would be useful to have the docs. However, because of the use of the CLI override feature being prominently featured this seems a bit more advanced for a new customer. Perhaps the Logger utility page is not the best place for it. Instead, could you add this under Guides and link to it from the Logger page?

2022-12-09 22:21 UTC, ktmdan commented
Updated PR moved to Guides and added a Link under logging.

2022-12-09 22:40 UTC, ktmdan commented
Also cspell should ignore code IMO.

2023-01-30 20:50 UTC, josefaidt commented on src/fragments/guides/utilities/logger-cloudwatch.mdx
> +amplify custom project
```suggestion
amplify override project
```

2023-01-30 20:52 UTC, josefaidt commented on src/fragments/guides/utilities/logger-cloudwatch.mdx
> +            "Resource": "arn:aws:logs:*:<ACCOUNT ID>:log-group:weblogs"
can we create a reference to the account ID here to mitigate the need of hardcoding? perhaps `cdk.Stack.of(this).account`?

2023-01-30 20:53 UTC, josefaidt commented on src/fragments/guides/utilities/logger-cloudwatch.mdx
> +Modify the file amplify/backend/auth/userPoolGroups/override.ts with this (be sure to replace your account id):
```suggestion
Modify the file `amplify/backend/auth/userPoolGroups/override.ts` with the following (be sure to replace your account id):
```

2023-01-30 20:54 UTC, josefaidt commented on src/fragments/guides/utilities/logger-cloudwatch.mdx
> +amplify auth override
```suggestion
amplify override auth
```

minor nit, either works, but `amplify <action> <category>` is primarily used elsewhere

2023-01-30 20:55 UTC, josefaidt requested changes
Hey @ktmdan apologies for the delay here! I left a few comments, and was also curious as to whether this can be expanded to be included in the guides for other languages/platforms as well? This topic appears framework/language-agnostic

2023-01-30 22:22 UTC, josefaidt commented on src/fragments/lib/utilities/js/logger-cloudwatch.mdx
> +For a guide on how to set up Cloudwatch Logging, visit [Cloudwatch Logging](/guides/utilities/logging)
```suggestion
## CloudWatch Logging

For a guide on how to set up CloudWatch Logging, visit the [CloudWatch Logging guide](/guides/utilities/logging)
```

2023-01-30 22:23 UTC, josefaidt commented on src/fragments/guides/utilities/logger-cloudwatch.mdx
> +export const CloudLogger = new Logger("app");
can we include the `Logger` and `Amplify` class imports in this example to enable easy copy/paste?

2023-01-30 22:26 UTC, ktmdan commented
This request was so long ago I no longer have the time to work on this.

2023-01-30 22:26 UTC, closed without merging

2023-01-30 23:19 UTC, abdallahshaban557 commented
Hi @ktmdan  - apologies for not getting to your PR earlier. We are working on improving the logger (including our documentation) for developers needing to send logs to Cloudwatch.