chore: Update CODEOWNERS
aws-amplify/docs pull request #4587
Opened 2022-09-15 18:30 UTC by palpatim

Add @aws-amplify/developer-advocates as CODEOWNERS for all paths

_Issue #, if available:_

_Description of changes:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-15 18:39 UTC, timngyn approved these changes
Looks good to me!!

2022-09-19 20:23 UTC, timngyn commented on .github/CODEOWNERS
> +/src/fragments/guides @aws-amplify/developer-advocates @aws-amplify/amplify-support-eng @aws-amplify/developer-advocates
Just noticed that, the `guides` routes already has `aws-amplify/developer-advocates` :
- `/src/pages/guides`
- `/src/fragments/guides`

2022-10-19 21:43 UTC, katiegoines requested changes
@palpatim - Lines 5 and 13 list `@aws-amplify/developer-advocates` twice. May I remove the duplicate? Thanks!

2022-11-09 19:55 UTC, katiegoines commented on .github/CODEOWNERS
> +/src/pages/guides @aws-amplify/developer-advocates @aws-amplify/amplify-support-eng @aws-amplify/developer-advocates
```suggestion
/src/pages/guides @aws-amplify/developer-advocates @aws-amplify/amplify-support-eng
```

2022-11-09 19:55 UTC, katiegoines commented on .github/CODEOWNERS
> +/src/fragments/guides @aws-amplify/developer-advocates @aws-amplify/amplify-support-eng @aws-amplify/developer-advocates
```suggestion
/src/fragments/guides @aws-amplify/developer-advocates @aws-amplify/amplify-support-eng
```

2022-11-09 19:56 UTC, katiegoines approved these changes

2022-11-09 20:02 UTC, closed without merging