feat: restructure cli docs to move 'troubleshooting' guides to the top level, and adding redirects for existing locations to keep from breaking CLI links
aws-amplify/docs pull request #4621
Opened 2022-09-28 21:57 UTC by alharris-at

_Issue #, if available:_
N/A

_Description of changes:_
The intent of this change is to modify the structure of the CLI docs to make it easier to find our troubleshooting guides. Today there are a few, but they're nested in the 'project structure' directory, making it a little tricky to find. This PR is limited to moving those pages, and updating the nav structure/inserting redirects, but I'd like to refactor where the content lives as well, a lot of the 'general' troubleshooting guides really ARE related to graphql, and we could probably do with a general 'deployment issues' guide.

The low level changes in this PR are:
* Updates to directory structure to move /cli/project/troubleshooting to /cli/troubleshooting/general, and /cli/graphql/troubleshooting/ to /cli/troubleshooting/graphql.
* Updates to directory structure adding nav elements for /cli/troubleshooting
* Add temp redirects (307) to old routes to allow old CLI versions not to break
* Update internal links to point to the new routes.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-28 22:03 UTC, jhockett approved these changes

2022-09-29 18:22 UTC, rachelnabors commented
This is a pretty big IA change proposal. 

1) Are you proposing moving the trouble shooting pages for each feature category to a "Troubleshooting" top level nav item (next to "Libraries" and "Getting Started") section as opposed to keeping them next to the technologies people may need help troubleshooting?
2) What is your reasoning behind this? Seems like as a learner running into problems with something, having troubleshooting guides in the section I'm reading would be easier to find than going to a new section of the site. Are you observing a particular behavior?

2022-09-29 21:38 UTC, ykethan commented
hey @rachelnabors, adding some information on the issue. Currently, on the Amplify docs website we can observe that the libraries already implements a troubleshooting section at the top level. The PR would enable consistency across docs.

libraries:
![image](https://user-images.githubusercontent.com/87995712/193142830-693f5a42-1967-4f82-86b8-84e6a2c6686a.png)

CLI:
![image](https://user-images.githubusercontent.com/87995712/193143658-08674acb-d0ff-4659-ad44-6a418efce6e7.png)

> "Troubleshooting" top level nav item (next to "Libraries" and "Getting Started") section

love the idea, but this will need some discussion. 

the troubleshooting docs could start with the following structure in the CLI section.

Top level Troubleshooting category section

1. General issues Page
Providing information on general troubleshooting issues such as installation, OS related, general pointers on what we support and best practices.
2. GraphQL issues Page
Providing information on GraphQL specific issues such as GSI, modelling issues.
3. CLI issues Page.
Providing information on issues present in the CLI categories such as storage resource, Lambda functions and other related category issues. 

Additionally, currently the troubleshooting for GraphQL is present under the GraphQL section and the Project level section(though this occurs on a push but is related to GraphQL). 

Felt this would be a cleaner way to find troubleshooting information. @alharris-at would this align with the implementation and idea?

2022-09-29 23:10 UTC, alharris-at commented
I'll +1 the reasoning that Sai listed. Primarily there are 2 key concerns I have today. 1) General CLI troubleshooting is embedded inside a section labeled `Project-Level Configuration` which is easy to forget, and tough to guess that that would be where you're looking (even as somebody reasonably familiar w/ our docs). 2) Secondary troubleshooting guides are actually unlisted today (so there exists a graphql troubleshooting guide), but you can't get to it until you've found that previous `/cli/project/troubleshooting` route, then clicked through a link to land there.

But yeah, my general reasoning is that currently it's tough to find these guides, despite them having useful information which could help customers self-service on common issues that aren't yet solved systematically.

Also, because my google-fu was weak today, what does IA stand for in this context?

2022-09-30 14:36 UTC, ykethan commented
Hey @alharris-at, IA in this context means information architecture.

2022-10-01 18:23 UTC, rachelnabors commented
The pictures help, thanks for the clarification!

### IA terminology note…

“Top-level” refers to the very top of the information architecture—which is
represented by the horizontal navigation bar for our site. I can see here
you’re describing moving them out the tertiary navigation (sub nav items)
into the secondary navigation (sidebar).

### To be clear…

I support keeping troubleshooting sections near the things they cover in
the IA—Just in Time troubleshooting when you get stuck following a guide
for implementing auth—not moving them to a disconnected and consolidated
island.

### However…

In the future, we will be merging the content in CLI and Libraries into the
Guides section—the CLI section will be more of a manual, and the guides
will show people how to accomplish tasks using both CLI and Studio with
Libraries. In this format, where would you see this troubleshooting content
living?
--

2022-10-07 16:58 UTC, rachelnabors requested changes
I had a moment to discuss this with one of our DXEs today, and a few thoughts.

## The problem that this PR is really trying to solve

People are requesting support/filing bugs for things that already have answers in our troubleshooting docs. Somehow, they either aren't able to find this information before they reach out for help.

## More research needed

A longterm solution requires a little more research to discover:
* Where are people looking when they run into trouble? (Google? Stack Overflow? Our site search? For a "trouble shooting" section?
* Would having all this content in a single location solve this problem? Or would the problem remain? Would it cause new problems ("I'm in the GraphQL section and having a problem, but I don't see any troubleshooting guides in the section...")?

### Big changes ahead

Because the structure of the content is about to rapidly change, moving all of the troubleshooting documentation to a single location would run the risk of then having to re-move all that information again—"content thrash." It would be an expensive experiment.

### MVP/vetting a possible solution

So I recommend making a single "Troubleshooting" page that lists all our troubleshooting pages. It will live under **Guides** and will can be linked to from our File A Bug flow. If that reduces the number of issues being filed, we'll have good signal that a centralized hub for troubleshooting is helping. If not, we will have saved ourselves content thrash and know we need more research, likely in the form of a few conversations with the people filing some of these bugs.

## Change request

* Create a new PR for a Troubleshooting index that lives under Guides
* Add link to check list for filing a bug
* Close this PR (we can always reopen it)

2022-10-27 19:38 UTC, katiegoines commented
Hi @alharris-at - Wanted to bump this re: @rachelnabors requested changes. Thank you!

2022-11-09 18:46 UTC, alharris-at commented
Thanks, given the impending rapid changes. I'll close this for now as suggested. For the checklist for filing a bug, I think most repos already define this in-place, so probably no need to add that to the docs. I'm okay to sit and wait for now.

2022-11-09 18:46 UTC, closed without merging