All instances of "Amplify app/application" have been changed to "Amplify Project"
aws-amplify/docs pull request #4694
Opened 2022-10-12 14:40 UTC by ledwinbatista

…ify Project"

_Issue #, if available:_

_Description of changes:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-18 18:49 UTC, katiegoines approved these changes
LGTM

2022-10-21 23:35 UTC, katiegoines approved these changes

2022-10-22 00:17 UTC, rachelnabors requested changes
Let's consistently use all lowercase "project," as in "your Amplify project," not "your Amplify Project."

2022-10-27 19:34 UTC, katiegoines requested changes
Made suggestions to address the changes @rachelnabors requested. Thanks!

2022-10-27 19:34 UTC, katiegoines commented on src/fragments/lib/auth/common/sms/flows.mdx
> +There are a few ways to integrate phone numbers into an Amplify Project's sign-in and verification process.
```suggestion
There are a few ways to integrate phone numbers into an Amplify project's sign-in and verification process.
```

2022-10-27 19:34 UTC, katiegoines commented on src/pages/cli/hosting/hosting.mdx
> +If you select Amplify Console for hosting your Amplify Project in the `amplify add hosting` flow, there are two stages you can select from as a part of the flow:
```suggestion
If you select Amplify Console for hosting your Amplify project in the `amplify add hosting` flow, there are two stages you can select from as a part of the flow:
```

2022-10-27 19:34 UTC, katiegoines commented on src/pages/cli/hosting/hosting.mdx
> +If you select Amazon S3 & Amazon Cloudfront for hosting your Amplify Project in the `amplify add hosting` flow, there are two stages you can select from as a part of the flow:
```suggestion
If you select Amazon S3 & Amazon Cloudfront for hosting your Amplify project in the `amplify add hosting` flow, there are two stages you can select from as a part of the flow:
```

2022-10-27 19:34 UTC, katiegoines commented on src/pages/cli/hosting/hosting.mdx
> +If you select Amazon S3 & Amazon Cloudfront for hosting your Amplify Project in the `amplify add hosting` flow, the frontend build artifacts will be uploaded to the S3 hosting bucket, and then if Ama
```suggestion
If you select Amazon S3 & Amazon Cloudfront for hosting your Amplify project in the `amplify add hosting` flow, the frontend build artifacts will be uploaded to the S3 hosting bucket, and then if Amazon CloudFront is enabled along with it, the `amplify publish` command executed with the `--invalidateCloudFront` or `-c` flag will send an invalidation request to the Amazon CloudFront service to invalidate its cache.
```

2022-10-27 19:35 UTC, katiegoines approved these changes

2022-11-02 00:20 UTC, rachelnabors approved these changes
![hacktober-amplify-2022 (1)](https://user-images.githubusercontent.com/236306/199365747-53290c85-e669-45d2-b3ac-43ab3a99d1ea.gif)

Thanks so much for contributing to our docs for Hacktoberfest! We appreciate all the care and effort you put into this PR!

2022-11-02 00:20 UTC, merged