issue 4690 - Replace Amplify app with Amplify project
aws-amplify/docs pull request #4705
Opened 2022-10-14 14:47 UTC by KazChe

_Issue #, if available:_
4690
_Description of changes:_
Replace `Amplify app` with `Amplify project`
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-14 16:54 UTC, siegerts commented
Hi @KazChe , thanks for opening. There is already an open PR to address this issue (#4694). Leaving this open for now until review.

2022-10-22 00:24 UTC, rachelnabors requested changes

2022-10-22 00:24 UTC, rachelnabors commented on src/fragments/start/getting-started/vue/data-model.mdx
> +This will open your Amplify project project in the AWS service console. Choose the **API** tab to view your AppSync API. Clicking on the API, will open the AWS AppSync console where you can run Queri
Duplicate "project"

2022-10-22 00:24 UTC, rachelnabors commented on src/pages/cli/graphql/troubleshooting.mdx
> +| --- | --- | --- |
Looks like some serious code formatting happening. It would be great if this could be limited to just updating the copy!

2022-11-02 00:29 UTC, rachelnabors commented
It looks like the other PR took care of these. So I will close it for now. Thank you very much for your PR. I hope you will come try Amplify in the future!

2022-11-02 00:29 UTC, closed without merging