Fix(Auth): Add custom auth android documentation
aws-amplify/docs pull request #4816
Opened 2022-11-10 18:45 UTC by gpanshu

_Issue #, if available:_

_Description of changes:_
Currently the Custom Auth flow is missing from Android documentation. This adds it.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-10 18:54 UTC, sktimalsina requested changes

2022-11-10 18:54 UTC, sktimalsina commented on src/fragments/lib/auth/android/signin_with_custom_flow/10_cli_setup.mdx
> +  Note that the `sendChallengeCode` method is empty, you can use AWS service
```suggestion
  Note that the `sendChallengeCode` method is empty. You can use AWS service
```

2022-11-10 18:54 UTC, sktimalsina commented on src/fragments/lib/auth/android/signin_with_custom_flow/10_cli_setup.mdx
> +Amazon Cognito invokes the Create Auth Challenge trigger after Define Auth Challenge to create a custom challenge. In this lambda trigger you define the challenge to present to the user. `privateChal
is `xcode` typo here?

2022-11-10 18:54 UTC, sktimalsina commented on src/fragments/lib/auth/android/signin_with_custom_flow/30_confirmSignup.mdx
> +```swift
swift

2022-11-10 19:44 UTC, div5yesh commented on src/fragments/lib/auth/android/signin_with_custom_flow/20_signup.mdx
> +func signUp(username: String, email: String) async {
swift code in Android page.

2022-11-11 17:19 UTC, gpanshu commented on src/fragments/lib/auth/android/signin_with_custom_flow/20_signup.mdx
> +func signUp(username: String, email: String) async {
resolved

2022-11-11 17:19 UTC, gpanshu commented on src/fragments/lib/auth/android/signin_with_custom_flow/30_confirmSignup.mdx
> +```swift
resolved

2022-11-11 17:20 UTC, gpanshu commented on src/fragments/lib/auth/android/signin_with_custom_flow/10_cli_setup.mdx
> +Amazon Cognito invokes the Create Auth Challenge trigger after Define Auth Challenge to create a custom challenge. In this lambda trigger you define the challenge to present to the user. `privateChal
resolved

2022-11-11 17:21 UTC, gpanshu commented on src/fragments/lib/auth/android/signin_with_custom_flow/10_cli_setup.mdx
> +  Note that the `sendChallengeCode` method is empty, you can use AWS service
resolved

2022-11-11 18:23 UTC, tjleing approved these changes

2022-11-11 18:52 UTC, sktimalsina approved these changes

2022-11-11 19:12 UTC, katiegoines approved these changes
Approved with one very nit suggestion.

2022-11-11 19:12 UTC, katiegoines commented on src/fragments/lib/auth/android/signin_with_custom_flow/10_cli_setup.mdx
> +  Note that the `sendChallengeCode` method is empty. You can use AWS service
```suggestion
  Note that the `sendChallengeCode` method is empty. You can use an AWS service
```

2022-11-11 19:39 UTC, merged