feat(api): add code samples 1/2
aws-amplify/docs pull request #4881
Opened 2022-11-22 17:30 UTC by iartemiev

_Issue #, if available:_

_Description of changes:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-23 17:17 UTC, katiegoines approved these changes

2022-12-19 19:21 UTC, josefaidt requested changes
Hey @iartemiev :wave: I like the addition of the code examples, however I'm concerned whether the addition strays from the intent of this doc.

Despite the concern there are a few differences between the examples including:

- use of imports (some examples import `API` or `awsExports` where others do not)
- use of `graphqlOperation`
- use of named imports vs `queries.createPost`
- use of try/catch

2023-02-20 14:13 UTC, iartemiev commented
Hey @josefaidt re:
> I like the addition of the code examples, however I'm concerned whether the addition strays from the intent of this doc.

@renebrandel requested that we include clientside snippets in the CLI docs. I'd discuss with him if you feel strongly that we shouldn't do that.

2023-02-20 16:18 UTC, josefaidt approved these changes

2023-02-20 16:18 UTC, josefaidt commented
Hey @iartemiev thanks for clarifying, that makes sense!

2023-03-22 13:09 UTC, renebrandel approved these changes

2023-03-22 17:39 UTC, katiegoines approved these changes

2023-03-23 17:58 UTC, renebrandel approved these changes

2023-03-23 17:59 UTC, katiegoines approved these changes

2023-03-23 17:59 UTC, merged