Add Coroutines and Rx docs for Geo category
aws-amplify/docs pull request #4923
Opened 2022-12-06 19:34 UTC by mattcreaser

_Description of changes:_ 
- Added documentation for using the new Coroutines and RxJava APIs for the Geo category
- Removed import statements from examples for consistency with other category docs

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-17 17:41 UTC, eeatonaws requested changes

2023-01-17 17:41 UTC, eeatonaws commented on src/fragments/lib/geo/android/getting_started/40_init_geo.mdx
> +}
This code block looks like Kotlin code, but I think it should be Java when using RxJava.

2023-03-23 14:21 UTC, hdworld11 submitted a review, later dismissed

2023-03-23 15:16 UTC, eeatonaws approved these changes

2023-03-23 15:46 UTC, hdworld11 approved these changes

2023-03-23 17:14 UTC, katiegoines approved these changes

2023-03-23 17:14 UTC, merged