feat: enable raw HTML strings in sidenav links
aws-amplify/docs pull request #4930
Opened 2022-12-07 23:54 UTC by josefaidt

_Description of changes:_

This PR aims to enable the usage of raw HTML strings inside `directory.js` in order to render inline code blocks inside sidenav link items. 

It introduces a use of `dangerouslySetInnerHTML` in the DirectoryGroup class component, however it first validates whether the supplied string contains an inline code block. 

<img width="281" alt="image" src="https://user-images.githubusercontent.com/5033303/205193715-99c400c1-db8b-47ae-9ee7-3d8a5043ef61.png">

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-08 04:01 UTC, rachelnabors commented
I. Love. It.

2022-12-09 21:26 UTC, timngyn requested changes
Hey @josefaidt, thank you for this! I think some of the tests are failing because you updated `directory.js`. I think the tests might need to be updated to handle the new `require()` statement you added.

2022-12-14 08:51 UTC, jacoblogan approved these changes

2022-12-14 18:30 UTC, timngyn approved these changes
LGTM!

2022-12-14 18:45 UTC, merged