add react native polyfill to getting started
aws-amplify/docs pull request #5097
Opened 2023-02-06 22:40 UTC by dpilch

#### Description of changes:

Add instructions to include missing polyfill for react native getting started.

#### Related GitHub issue #, if available:

https://github.com/aws-amplify/amplify-js/issues/10764

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [x] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [x] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [x] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

            
### When this PR is ready to merge, please check the box below
- [x] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-02-07 01:44 UTC, dpilch commented
I edited the wrong files. This should be on the DataStore getting started doc. Please ignore until fixed.

2023-02-07 15:57 UTC, dpilch commented
Fixed to use only the DataStore getting started pages now.

2023-02-07 18:50 UTC, timngyn commented on src/fragments/lib/datastore/react-native/getting-started/polyfills.mdx
> +React Native is missing some standard library funcationality that is required by DataStore.
Small typo that's causing the spellcheck to fail:

```suggestion
React Native is missing some standard library functionality that is required by DataStore.
```

2023-02-09 17:19 UTC, alharris-at approved these changes

2023-02-19 00:08 UTC, david-mcafee requested changes
Minor question.

2023-02-19 00:08 UTC, david-mcafee commented on src/fragments/lib/datastore/react-native/getting-started/polyfills.mdx
> +```
cc @renebrandel - wanted to get your thoughts on phrasing here.

2023-02-22 21:14 UTC, dpilch commented on src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx
> +expo install aws-amplify @aws-amplify/datastore-storage-adapter expo-sqlite expo-file-system @react-native-community/netinfo @react-native-async-storage/async-storage
From my testing when using expo `Symbol.asyncIterator` is available so `core-js` is not needed.

2023-02-28 22:37 UTC, david-mcafee submitted a review, later dismissed
Would like to get @renebrandel's opinion on `src/fragments/lib/datastore/react-native/getting-started/polyfills.mdx`, but otherwise looks good to me!

2023-02-28 22:48 UTC, svidgen approved these changes

2023-03-01 17:55 UTC, renebrandel commented on src/fragments/lib/datastore/react-native/getting-started/polyfills.mdx
> +### Add Polyfills
Add required polyfills

2023-03-01 17:56 UTC, renebrandel commented on src/fragments/lib/datastore/react-native/getting-started/polyfills.mdx
> +React Native is missing some standard library functionality that is required by DataStore.
React Native is missing some JavaScript standard library functionality that DataStore depends on. Add the following to the entry point of your app to polyfill these missing functionalities:

2023-03-01 17:56 UTC, renebrandel requested changes
suggested phrasing updates

2023-03-01 20:42 UTC, renebrandel approved these changes

2023-03-01 22:56 UTC, merged