added usage example for permission boundary.
aws-amplify/docs pull request #5113
Opened 2023-02-14 19:44 UTC by ykethan

#### Description of changes:
Added an example for permissions boundary using aws managed policy for DynamoDb

#### Related GitHub issue #, if available:
closes: https://github.com/aws-amplify/docs/issues/4042

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [x] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [x] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [x] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br />
      _ref: MDX: `[link](https://link.com)`
            HTML: `<a href="https://link.com">link</a>`_
            
### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-02-15 22:04 UTC, edwardfoyle requested changes
Left a few comments but my main feedback is that permission boundaries are not meant to scope down what a developer can do in a project but rather what a role that the CLI creates can do. To scope down what a developer can do, the permissions attached to the IAM user/role that the developer is using should be adjusted accordingly. The permission boundary is a safeguard against, say the CLI creating a lambda execution role in a dev environment that accidentally grants access to a prod DynamoDB table.

2023-02-15 22:04 UTC, edwardfoyle commented on src/pages/cli/project/permissions-boundary.mdx
> +We can verify if the permissions boundary have been applied by checking the AWS IAM console for the `authRole` and `unauthRole` created by Amplify CLI.
```suggestion
Verify the permissions boundary have been applied by checking the AWS IAM console for the `authRole` and `unauthRole` created by Amplify CLI.
```

2023-02-19 19:50 UTC, ykethan commented on src/pages/cli/project/permissions-boundary.mdx
> +For this example lets consider a scenario where the team wants to create a environment thats allows the developers to only work with DynamoDB resources. We can use the [AWS managed](https://us-east-1
Thank you for the info @edwardfoyle, modified the use case accordingly.

2023-03-06 17:11 UTC, sdstolworthy commented on src/pages/cli/project/permissions-boundary.mdx
> +Verify if the permissions boundary have been applied by checking the AWS IAM console for the `authRole` and `unauthRole` created by Amplify CLI.
```suggestion
Verify if the permissions boundary has been applied by checking the AWS IAM console for the `authRole` and `unauthRole` created by Amplify CLI.
```

2023-03-06 17:11 UTC, sdstolworthy commented on src/pages/cli/project/permissions-boundary.mdx
> +Add a DynamoDB table, run:
```suggestion
To add a DynamoDB table, run:
```

2023-03-06 17:11 UTC, sdstolworthy commented on src/pages/cli/project/permissions-boundary.mdx
> +Push the resources, run:
```suggestion
To push the resources, run:
```

2023-03-06 17:12 UTC, sdstolworthy commented on src/pages/cli/project/permissions-boundary.mdx
> +In non-interactive shells use
```suggestion
In non-interactive shells, use:
```

2023-03-06 17:16 UTC, sdstolworthy commented on src/pages/cli/project/permissions-boundary.mdx
> +If we create resources that are outside the scope of allowed resources on permissions boundary, for example a Cognito resource. The next `amplify push` will fail.
Is Permissions Boundary a proper noun or not? The casing is mixed in the documentation. In these new additions, it is lower cased "permissions boundary". In the existing documentation, it is Title Case in the existing language in this file. 

https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html

The docs here lead me to believe it should be lower case in all uses.

2023-03-06 17:17 UTC, sdstolworthy requested changes
Mostly nits, but the mixed casing should be addressed and made uniform.

2023-03-21 18:40 UTC, josefaidt approved these changes

2023-03-22 13:20 UTC, renebrandel approved these changes

2023-03-22 17:42 UTC, sdstolworthy approved these changes

2023-03-27 18:47 UTC, edwardfoyle requested changes
Previous comment is still relevant

2023-04-26 12:19 UTC, ykethan commented
closing this to create a new PR.

2023-04-26 12:19 UTC, closed without merging