Predictions/transcribe language support
aws-amplify/docs pull request #5147
Opened 2023-02-23 19:19 UTC by kvramyasri7

#### Description of changes:
This change links all the languages specific features for transcribe
#### Related GitHub issue #, if available:
#4367 

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [X] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [X] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [X] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [X] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br />
      _ref: MDX: `[link](https://link.com)`
            HTML: `<a href="https://link.com">link</a>`_
            
### When this PR is ready to merge, please check the box below
- [X] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-02-23 20:30 UTC, abdallahshaban557 submitted a review, later dismissed
LGTM!

2023-02-27 18:12 UTC, stocaaro requested changes

2023-03-06 22:54 UTC, kvramyasri7 commented on src/fragments/lib/predictions/js/transcribe.mdx
> +To view the complete list of all the supported languages and language specific features refer to [other language options](https://docs.aws.amazon.com/transcribe/latest/dg/supported-languages.html)
Added. Thanks.

2023-03-07 18:38 UTC, stocaaro approved these changes

2023-03-07 18:51 UTC, katiegoines approved these changes

2023-03-07 18:51 UTC, merged