feat(data): update PR template with E2E test check for code examples
aws-amplify/docs pull request #5161
Opened 2023-02-27 18:21 UTC by david-mcafee

#### Description of changes:
While adding TypeScript examples to our DataStore docs, I noticed several existing code examples that were broken. See:
https://github.com/aws-amplify/docs/issues/5157
https://github.com/aws-amplify/docs/pull/5155
https://github.com/aws-amplify/docs/pull/5140/files

Updating our PR template with a check for new / updated E2E tests for all new / updated code examples in the docs.

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br />
      _ref: MDX: `[link](https://link.com)`
            HTML: `<a href="https://link.com">link</a>`_
            
### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-02-27 18:27 UTC, david-mcafee commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> _ref: MDX: `[link](https://link.com)` HTML: `<a href="https://link.com">link</a>`_
`link.com` is an actual website, but not owned by Amplify.

2023-02-27 20:06 UTC, jimblanc submitted a review, later dismissed

2023-02-27 22:34 UTC, stocaaro approved these changes

2023-02-28 06:23 UTC, rachelnabors requested changes
I have questions... How are non-Amplify team members expected to participate in this? Is there a way to permanently associate a test with a code snippet? How does creating E2E tests for code snippets impact our writing guidelines?

2023-03-01 00:26 UTC, david-mcafee commented
> I have questions... How are non-Amplify team members expected to participate in this? Is there a way to permanently associate a test with a code snippet? How does creating E2E tests for code snippets impact our writing guidelines?

@rachelnabors - when you say `non-Amplify team members`, do you mean external contributors? If so, we would not expect them to write E2E tests. However, we _would_ expect an Amplify team member to add / update the E2E tests as necessary.

`Is there a way to permanently associate a test with a code snippet?` - we don't currently have a mechanism for this that I'm aware of, at least with regards to the JS library, though it's something we can certainly explore.

`How does creating E2E tests for code snippets impact our writing guidelines?` - if you are referring to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md), I can update that, as well.

Let me know if you have further questions!

2023-03-14 19:01 UTC, rachelnabors commented
I see. I recommend that, rather than adding another tick box that doesn't mean anything to external contributors, we add mechanisms to ensure each line of code added has an associated test, like we use to ensure PRs that remove files have redirects. That would be a good part of a project we're working on. I'll put you in touch with the right folks on the effort.

2024-01-03 20:32 UTC, closed without merging

2024-01-03 20:32 UTC, hbuchel commented
Pulled out the fix for updating the `link.com` example link into [this separate PR](https://github.com/aws-amplify/docs/pull/6730). 

Closing this PR due to its age and the docs site has since been refactored. Please feel free to update with latest and re-open if you feel it is still relevant, thanks.