chore: fix Import cognito resource on studio
aws-amplify/docs pull request #5195
Opened 2023-03-02 21:15 UTC by ykethan

#### Description of changes:
PR updates information on importing a cognito resource. modifies existing information on the resource.
images have been added to show users how to import cognito resource.

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [x] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [x] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [x] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br />
      _ref: MDX: `[link](https://link.com)`
            HTML: `<a href="https://link.com">link</a>`_
            
### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-03-02 21:40 UTC, josefaidt commented on src/pages/console/auth/import.mdx
> +[Learn more about getting started with User Pools](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-started-with-cognito-user-pools.html) or [configuring a User Pool App Client](http
```suggestion
[Learn more about getting started with Cognito User Pools](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-started-with-cognito-user-pools.html) or [configuring a User Pool App Client](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html)
```

2023-03-02 21:41 UTC, josefaidt commented on src/pages/console/auth/import.mdx
> +Imported Amazon Cognito resource is particularly useful if you’re trying to do the following:
```suggestion
Importing an Amazon Cognito resource is particularly useful if you’re trying to do the following:
```

2023-03-03 20:08 UTC, johnpc requested changes

2023-03-03 20:08 UTC, johnpc commented on src/pages/console/auth/import.mdx
> +We can also use Amplify CLI to [import an Cognito identity pool resource](/cli/auth/import/).
In order to import the identity pool, do you also need to import the user pool? Might be worth pointing that out if so.

2023-03-03 20:08 UTC, johnpc commented on src/pages/console/auth/import.mdx
> +We can also use Amplify CLI to [import an Cognito identity pool resource](/cli/auth/import/).
Looks like a typo "an Cognito identity pool resource" should be "a Cognito identity pool resource"

2023-03-03 20:08 UTC, johnpc commented on src/pages/console/auth/import.mdx
> +We can also use Amplify CLI to [import an Cognito user pool resource](/cli/auth/import/).
typo - "an Cognito user pool"

2023-03-06 17:04 UTC, johnpc approved these changes

2023-03-06 17:11 UTC, josefaidt approved these changes

2023-03-06 17:13 UTC, wrpeck approved these changes

2023-03-06 17:45 UTC, katiegoines approved these changes

2023-03-06 17:45 UTC, merged