fix(android): Add minor improvements to android getting started guide
aws-amplify/docs pull request #5368
Opened 2023-04-11 16:02 UTC by sdhuka

#### Description of changes:

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [X] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [X] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [X] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [X] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-04-11 16:13 UTC, abdallahshaban557 approved these changes
LGTM!

2023-04-11 16:22 UTC, gpanshu commented on src/fragments/lib/project-setup/android/create-application/40_verifyAmplifyLibraries.mdx
> +Create a class by extending `Application` and override its `onCreate()` to to initialize Amplify in your application.
```suggestion
Create a class by extending `Application` and override its `onCreate()` to initialize Amplify in your application.
```

2023-04-11 16:23 UTC, gpanshu requested changes
minor comment

2023-04-11 16:25 UTC, dengdan154 approved these changes

2023-04-11 16:26 UTC, abdallahshaban557 approved these changes
LGTM

2023-04-11 16:44 UTC, gpanshu approved these changes

2023-04-17 14:30 UTC, dengdan154 approved these changes

2023-04-17 14:38 UTC, hdworld11 approved these changes

2023-04-17 17:53 UTC, katiegoines approved these changes

2023-04-17 17:54 UTC, merged