feat(storage): Update list api documentation to add pagination examples
aws-amplify/docs pull request #5397
Opened 2023-04-18 15:26 UTC by sdhuka

#### Description of changes:
- Remove example for deprecated list API
- Add examples with `StoragePagedListOptions`

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [X] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [X] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [X] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-04-19 21:16 UTC, dengdan154 commented on src/fragments/lib/storage/android/list.mdx
> +You can list all of the objects uploaded under a given prefix by setting the pageSize. If the page size is set lower than the total file size available,
You can list all of the objects uploaded under a given prefix by setting the pageSize. If the pagSize is set lower than the total file size available,

2023-04-19 21:22 UTC, dengdan154 requested changes

2023-04-19 21:22 UTC, dengdan154 commented on src/fragments/lib/storage/android/list.mdx
> +You can list all of the objects uploaded under a given prefix by setting the pageSize. If the page size is set lower than the total file size available,
```suggestion
You can list all of the objects uploaded under a given prefix by setting the pageSize. If the pageSize is set lower than the total file size available,
```

2023-04-19 21:22 UTC, dengdan154 commented on src/fragments/lib/storage/android/list.mdx
> +        Log.i("MyAmplifyApp", "Next Token: ${result.nextToken}");
```suggestion
        Log.i("MyAmplifyApp", "Next Token: ${result.nextToken}")
```

2023-04-19 21:22 UTC, dengdan154 commented on src/fragments/lib/storage/android/list.mdx
> +        Log.i("AmplifyApplication", "Item: $it")
```suggestion
        Log.i("MyAmplifyApp", "Item: $it")
```

2023-04-19 21:22 UTC, dengdan154 commented on src/fragments/lib/storage/android/list.mdx
> +    Log.i("AmplifyApplication", "next token: ${result.nextToken}")
```suggestion
    Log.i("MyAmplifyApp", "next token: ${result.nextToken}")
```

2023-04-19 21:22 UTC, dengdan154 commented on src/fragments/lib/storage/android/list.mdx
> +);
Tabbing is inconsistent

2023-04-19 21:22 UTC, dengdan154 commented on src/fragments/lib/storage/android/list.mdx
> +);
Tabbing is inconsistent

2023-04-19 21:22 UTC, dengdan154 commented on src/fragments/lib/storage/android/list.mdx
>          Log.i("AmplifyApplication", "Item: $it")
```suggestion
        Log.i("MyAmplifyApp", "Item: $it")
```

2023-04-19 21:22 UTC, dengdan154 commented on src/fragments/lib/storage/android/list.mdx
> +    Log.i("AmplifyApplication", "next token: ${result.nextToken}")
```suggestion
    Log.i("MyAmplifyApp", "next token: ${result.nextToken}")
```

2023-04-20 15:07 UTC, dengdan154 approved these changes

2023-04-20 15:52 UTC, sdhuka commented
> @sdhuka, since a file was deleted from the `src/pages` and/or `src/fragments` directories, redirects might need to be set up so these previous pages do not 404. If redirects are needed, please answer these questions for each redirect that is needed:
> 
> * What is the source address of the redirect? (Where are you trying to redirect from?)
> * What is the target address of the redirect? (Where are you trying to redirect to?)
> * Type of redirect? 301 - permanent redirect or 302 - temporary redirect? (More info on Amplify Hosting redirects here: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html)

@timngyn @katiegoines No files are deleted in this PR, not sure why this bot picked it up?

2023-04-25 17:23 UTC, hdworld11 approved these changes

2023-04-26 18:24 UTC, katiegoines approved these changes

2023-04-26 18:24 UTC, merged