Amplify Android: replace deprecated id with identifier method
aws-amplify/docs pull request #5613
Opened 2023-07-01 01:02 UTC by ankpshah

#### Description of changes:
Replace deprecated id method by identifier method.
#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [x] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [x] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-07-03 15:01 UTC, eeatonaws reviewed
Thanks for updating the identifier method in the docs. Please remove the added try/catch around the Java and RxJava code blocks.

2023-07-03 17:25 UTC, eeatonaws commented on src/fragments/lib-v1/datastore/android/data-access/delete-snippet.mdx
> +try{
Formatting nit:
```suggestion
try {
```
Same comment for the `try` blocks below

2023-07-03 17:25 UTC, eeatonaws commented on src/fragments/lib-v1/datastore/android/data-access/delete-snippet.mdx
> +}catch (AmplifyException e) {
Formatting nit:
```suggestion
} catch (AmplifyException e) {
```
Same comment for the `catch` blocks below

2023-07-03 18:10 UTC, eeatonaws approved these changes

2023-07-03 18:30 UTC, tylerjroach requested changes
I don't believe any of the try/catches would ever throw unless in Kotlin Facade. The catches also all say that query failed, when some are delete/update operations.

2023-07-03 20:36 UTC, ankpshah commented
1. try/catch block is required to handle AmplifyException thrown by Where.identifier method. If unhandled, compiler will throw unhandled exception error.
2. Query failed log message is present in onQueryFailed argument. Delete and Update log messages respectively are present in onQueryResult argument of DataStore.Query method call.

2023-07-03 20:37 UTC, ankpshah commented
Have separated try catch block for Where.identifier followed by null check to make it simple to understand.

2023-07-03 20:40 UTC, tylerjroach approved these changes

2023-07-03 20:46 UTC, eeatonaws commented on src/fragments/lib-v1/datastore/android/data-access/delete-snippet.mdx
> +Amplify.DataStore.query(Post::class.java, Where.identifier(Post::class.java, "123"),
Try/catch block is needed for the Kotlin Callbacks code samples with Where.identifier

2023-07-03 20:56 UTC, eeatonaws approved these changes

2023-07-03 20:56 UTC, eeatonaws commented on src/fragments/lib-v1/datastore/android/data-access/delete-snippet.mdx
> +Amplify.DataStore.query(Post::class.java, Where.identifier(Post::class.java, "123"),
No compiler warning or error without try/catch block for Kotlin Callbacks

2023-07-05 17:04 UTC, hdworld11 approved these changes

2023-07-05 17:28 UTC, katiegoines approved these changes

2023-07-05 17:28 UTC, merged