JTBD Data Review 4 Guides
aws-amplify/docs pull request #5800
Opened 2023-08-23 00:51 UTC by heatheramz

#### Description of changes: Update with the 4 new guides split apart. Also includes examples of inline filter.

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-08-23 01:13 UTC, heatheramz reviewed
@renebrandel Updated the guides to the 4 we discussed and incorporated the new inline filter. Ready for your review - there are a few todos that we noted to come back to in next review which are marked.

2023-08-23 01:13 UTC, heatheramz commented on src/pages/lib/graphqlapi/mutate-data/q/platform/[platform].mdx
@renebrandel This is the one guide where I interwove all the platforms with the new inline filter. This is more a working demo on how this can work and for testing. I thought this might work as an authoring and editing test with you and Jim. I used this one b/c it was the most simple but we may want to consider what this would look like with more cross-platform explainer content. We can also roll this back to be like the next two pages for publication and just link to the mobile fragments

2023-08-23 01:13 UTC, heatheramz commented on src/pages/lib/graphqlapi/query-data/q/platform/[platform].mdx
@renebrandel This one only has the new content under JS and React Native inline filter for the guide. The rest of the platforms use their existing fragments without any guide language or blending.

2023-08-23 01:13 UTC, heatheramz commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
@renebrandel This one only has the new content under JS and React Native inline filter for the guide. The rest of the platforms use their existing fragments without any guide language or blending.

2023-08-23 01:13 UTC, heatheramz commented on src/pages/lib/graphqlapi/query-data/q/platform/[platform].mdx
> +[TODO]: # (Follow up on the following codegen section for better placement. May be shifted to a different section.)
@renebrandel Another codegen section we had marked to revisit

2023-08-23 01:13 UTC, heatheramz commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +[TODO]: # (Reminder that in last review noted opportunity to reduce this into a short blurb and move the main content to "custom business logic")
@renebrandel Just calling out this reminder from last review

2023-08-29 22:46 UTC, renebrandel requested changes

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/query-data/q/platform/[platform].mdx
> +As your data grows, you will want to filter and paginate at the AWS AppSync level instead of on the client. Fortunately, this is already built in to `API.graphql`, but you need to understand the sche
```suggestion
As your data grows, you will want to filter and paginate your list queries. Fortunately, this is already built in to the Amplify-generated GraphQL API.
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/query-data/q/platform/[platform].mdx
> +You can find the input schemas in the Docs pane of the GraphQL explorer or inside your autogenerated `/graphql` folder. They look like this:
the content below here might be a bit too technical as the starting point. (and also duplicative with paginate section lower down.)

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +Subscriptions is a GraphQL feature that allows the server to send data to its clients when a specific event happens. You can enable real-time data integration in your app with a subscription.
```suggestion
Subscriptions is a GraphQL feature that allows the server to send data to its clients when a specific event happens. For example, you can subscribe to an event when a new record is created, updated, or deleted via the API. You can enable real-time data integration in your app with a subscription.
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +  graphqlOperation(subscriptions.onCreateTodo)
```suggestion
  { query: subscriptions.onCreateTodo }
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +const sub = API.graphql<GraphQLSubscription<OnCreateTodoSubscription>>(
```suggestion
const createSub = API.graphql<GraphQLSubscription<OnCreateTodoSubscription>>(
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +sub.unsubscribe();
```suggestion
createSub.unsubscribe();
updateSub.unsubscribe();
deleteSub.unsubscribe();
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +import { Amplify, API, graphqlOperation } from 'aws-amplify';
```suggestion
import { Amplify, API } from 'aws-amplify';
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +  graphqlOperation(subscriptions.onDeleteTodo)
```suggestion
  { query: subscriptions.onDeleteTodo }
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +  graphqlOperation(subscriptions.onUpdateTodo)
```suggestion
  { query: subscriptions.onUpdateTodo }
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +  graphqlOperation(subscriptions.onCreateTodo)
```suggestion
  { query: subscriptions.onCreateTodo }
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +const sub = API.graphql(
```suggestion
const createSub = API.graphql(
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +   graphqlOperation(subscriptions.onUpdateTodo)
```suggestion
   { query: subscriptions.onUpdateTodo }
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +  graphqlOperation(subscriptions.onDeleteTodo)
```suggestion
  { query: subscriptions.onDeleteTodo }
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +sub.unsubscribe();
```suggestion
createSub.unsubscribe();
updateSub.unsubscribe();
deleteSub.unsubscribe();
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +When using **AWS AppSync** subscriptions, be sure that your AWS AppSync configuration is at the root of the configuration object, instead of being under the API:
I'm actually not sure if this is true anymore.

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +
```suggestion

## Filter real-time subscriptions server-side

```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +- Additionally, if you authorize via an array of groups (groups: [String]),
```suggestion
- Additionally, if you authorize via an array of groups (`groups: [String]`),
```

2023-08-29 22:46 UTC, renebrandel commented on src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
> +  const allTodos = await API.graphql<GraphQLQuery<ListTodosQuery>>({
TODO for me to change all the `graphqlOperations` patterns

2023-09-05 16:43 UTC, merged