Adding custom resource error message when deployed from studio
aws-amplify/docs pull request #5924
Opened 2023-09-21 17:54 UTC by sushpatg

#### Description of changes:
Amplify Studio does not allow deployments, if the project contains custom resources and fails with the following error
```
A flag to disable custom resources has been detected, please deploy from a different environment. at buildResource
```
Modifying the doc to include the error message and limitation

#### Related GitHub issue #, if available:[1032](https://github.com/aws-amplify/amplify-studio/issues/1032)

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [X] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [X] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [X] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-09-22 14:36 UTC, ykethan commented on src/pages/console/adminui/extend-cli.mdx
> +The above errors are encountered if an Amplify project has an `override.ts` file or [custom resources](https://docs.amplify.aws/cli/custom/cdk/) deployed in the project. Amplify Studio does not suppo
```suggestion
The errors mentioned above occur during deployment if your Amplify project contains an `override.ts` file or [custom resources](https://docs.amplify.aws/cli/custom/cdk/) deployed. Amplify Studio does not support deploying projects with override files or custom resources.
```

2023-09-22 14:41 UTC, ykethan commented on src/pages/console/adminui/extend-cli.mdx
> +To resolve this error, remove the `override.ts` file or custom resources and run `amplify push`. Alternatively, you can use Amplify CLI to build and push your resources. But you will not be able to d
```suggestion
To resolve this error, remove the `override.ts` file or any custom resources and run `amplify push`. Alternatively, you can use Amplify CLI to build and push your resources; however, deploying with Amplify Studio will not be possible.
```

2023-09-22 16:00 UTC, ykethan submitted a review, later dismissed

2023-09-22 20:42 UTC, sdstolworthy requested changes

2023-09-22 20:42 UTC, sdstolworthy commented on src/pages/console/adminui/extend-cli.mdx
> +The errors mentioned above occur during deployment if your Amplify project contains an `override.ts` file or [custom resources](https://docs.amplify.aws/cli/custom/cdk/) deployed. Amplify Studio does
```suggestion
The errors mentioned above occur during deployment if your Amplify project contains an `override.ts` file or [custom resources](https://docs.amplify.aws/cli/custom/cdk/) are deployed. Amplify Studio does not support deploying projects with override files or custom resources.
```

2023-09-22 20:42 UTC, sdstolworthy commented on src/pages/console/adminui/extend-cli.mdx
> +To resolve this error, remove the `override.ts` file or any custom resources and run `amplify push`. Alternatively, you can use Amplify CLI to build and push your resources; however, deploying with A
```suggestion
To resolve this error, remove the `override.ts` file and any custom resources from your project, then run `amplify push`. Alternatively, you can use Amplify CLI to build and push your resources; however, deploying with Amplify Studio will not be possible.
```

2023-10-04 18:42 UTC, sdstolworthy approved these changes

2023-10-04 18:48 UTC, wrpeck approved these changes
LGTM

2023-10-04 23:41 UTC, timngyn approved these changes

2023-10-04 23:41 UTC, merged