Getting Started/Setup - React, Angular, Vue & Vanilla JS
aws-amplify/docs pull request #6184
Opened 2023-11-03 00:32 UTC by nadetastic

#### Description of changes:

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-11-03 01:00 UTC, abdallahshaban557 approved these changes
LGTM

2023-11-06 14:08 UTC, renebrandel commented on src/fragments/cli-config.mdx
> +> If you are using CLI version < 12 go to [Configure CLI < 10.8.0](#configure-the-amplify-cli-version--1080)
Is this removed by error? The linked section seems to be deleted below.

2023-11-06 14:09 UTC, renebrandel commented on src/fragments/start/getting-started/angular/data-model.mdx
> +The GraphQL Transform Library provides custom directives you can use in your schema that allow you to do things like define data models, set up authentication and authorization rules, configure serve
```suggestion
Amplify's GraphQL API provides custom directives you can use in your schema that allow you to do things like define data models, set up authentication and authorization rules, configure serverless functions as resolvers, and more. In the example schema above, the `@model` directive is part of Amplify's [GraphQL API](/cli/graphql/data-modeling) functionality and the `@auth` directive determines what [authorization rules](/cli/graphql/authorization-rules/) to apply.
```

2023-11-06 14:10 UTC, renebrandel commented on src/fragments/start/getting-started/angular/data-model.mdx
> +Amplify.configure(amplifyconfig);
```suggestion
import amplifyconfig from './amplifyconfiguration.json';

Amplify.configure(amplifyconfig);
```

2023-11-06 14:30 UTC, renebrandel requested changes
Found issues in PR, going to push changes soon. Primarily subscriptions related.

2023-11-06 23:20 UTC, renebrandel commented on src/fragments/start/getting-started/reactnative/auth.mdx
>    const [formState, setFormState] = useState(initialFormState);
```suggestion
const client = generateClient();

const App = () => {
  const [formState, setFormState] = useState(initialFormState);
```

2023-11-06 23:20 UTC, renebrandel commented on src/fragments/start/getting-started/reactnative/auth.mdx
> +
```suggestion
const client = generateClient();
  
const App = () => {
```

2023-11-06 23:21 UTC, renebrandel commented on src/fragments/start/getting-started/reactnative/data-model.mdx
> +
```suggestion
const client = generateClient();

const App = () => {
```

2023-11-22 14:31 UTC, nadetastic commented
Changes merged Via Different PR - https://github.com/aws-amplify/docs/pull/6305

2023-11-22 14:31 UTC, closed without merging