adding gen 2 instructions for mySQL / postgreSQL support
aws-amplify/docs pull request #6600
Opened 2023-12-04 19:45 UTC by renebrandel

#### Description of changes:

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-02-19 21:20 UTC, stocaaro commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +    .handler(sql`
I'm unsure what the `sql` template string function is doing for us here. Is this a function that our library provides that should be added to the import above? Is this coming from somewhere else? What behavior does it provide?

Is this most similar to one of the following?
- https://github.com/andywer/squid?tab=readme-ov-file
- https://www.npmjs.com/package/sql-template-strings
- https://www.npmjs.com/package/sql-template-tag

I thought I might find this idiom in Prisma, but they appear to support raw sql as plain strings.

2024-02-19 21:22 UTC, stocaaro commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +    .handler(a.handler.inlineSql`
This also reads like a template string array function. Probably the long form of what is implied above. I would suppose that this is meant to indicate that we need a pattern to protect against sql injection. Is there a library that we intend to consume for this protection? If not consuming, are we patterning this behavior off of some other specific library?

2024-03-22 16:34 UTC, sundersc commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +npx amplify generate schema-from-database --connection-string MYSQL_CONNECTION_STRING --out amplify/data/schema.rds.ts
Changed the option name after the most recent API review.

```suggestion
npx amplify generate schema-from-database --connection-uri-secret MYSQL_CONNECTION_STRING --out amplify/data/schema.rds.ts
```

2024-03-28 18:02 UTC, renebrandel commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +rdsSchema.setSqlStatementFolderPath(path.join(__dirname, 'aurora-statements'))
```suggestion
rdsSchema.setSqlStatementFolderPath('./aurora-statements/'))
```

2024-04-02 20:46 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +npx amplify sandbox secret add MYSQL_CONNECTION_STRING
```suggestion
npx amplify sandbox secret set MYSQL_CONNECTION_STRING
```

2024-04-14 20:09 UTC, iartemiev requested changes

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +const combinedSchema = a.schema.combine([rdsSchema, ddbSchema])
New DX:

```suggestion
const modifiedRds = rdsSchema.relationships((models) => [
  models.Todo.addRelationships({
    // will be: a.hasMany("Comment", "todo_id")
    comments: a.hasMany("Comment").references("todo_id"),
    // will be: a.hasMany("Note", "todoId")    
    notes: a.hasMany("Note").references("todoId")
  })
]);
// highlight-end

const ddbSchema = a.schema({
   Note: a.model({
     content: a.string(),
     todoId: a.id()
     todo: a.belongsTo("Todo").references("todoId")
   })
})

const combinedSchema = a.schema.combine([modifiedRds, ddbSchema])
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +    .handler(a.handler.inlineSql`
```suggestion
    .handler(a.handler.inlineSql(`
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +rdsSchema.setSqlStatementFolderPath('./aurora-statements/'))
No longer supported. `a.handler.sqlReference('./relativePathToFile.sql')` is how we specify a path for the file containing SQL statements
```suggestion
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +    .authorization([a.allow.public()])
```suggestion
const modifiedRds = rdsSchema.addMutation({
  updateTodoBasedOnLocation: a.mutation()
    .arguments({
      lat: a.float(),
      long: a.float(),
      radiusInMeters: a.float(),
      todoChange: a.ref("Todo")
    })
    .returns(a.ref("Todo"))
    .handler(a.handler.sqlReference('./updateTodoBasedOnLocation.sql'))
    .authorization([a.allow.public()])
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +  rdsSchema
```suggestion
  modifiedRds
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +rdsSchema.models.Todo.authorization([a.allow.public()])
```suggestion
const modifiedRds = rdsSchema.setAuthorization((models) => [
  models.todo.authorization([a.allow.public()]),
  models.todo.fields.content.authorization([a.allow.private()]),
]);
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +  rdsSchema
```suggestion
  modifiedRds
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +rdsSchema.models.todos.fields.title.renameTo("content")
Same DX changes as above

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +    .handler(sql`
```suggestion
    .handler(a.handler.inlineSql(`
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +    `)
```suggestion
    `))
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +rdsSchema.addQueries({
```suggestion
const modifiedRds = rdsSchema.addQueries({
```

2024-04-14 20:09 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +  rdsSchema
```suggestion
  modifiedRds
```

2024-04-17 19:08 UTC, phani-srikar commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +import { schema as auroraSchema } from './schema.rds.ts';
Is there any particular reason for using `auroraSchema` versus a more general `sqlSchema`?

2024-04-17 19:43 UTC, phani-srikar commented on src/pages/gen2/build-a-backend/data/connect-to-existing-database/index.mdx
> +import { schema as rdsSchema } from './schema.rds.ts'
here and in other snippets, specifying `.ts` gives the following error in my VS Code IDE with default settings:
![Screenshot 2024-04-17 at 12 22 13 PM](https://github.com/aws-amplify/docs/assets/55896475/881260b7-4b18-4ba5-9776-b97a4e5d9a7f)
We could skip that extension and that resolves it.

2024-06-18 19:18 UTC, closed without merging