chore: update structure of migration guide
aws-amplify/docs pull request #6625
Opened 2023-12-07 17:09 UTC by erinleigh90

#### Description of changes:
Updates structure of migration guide to allow for easier access to category sections as well as better highlighting of category-specific migration guides.

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] iOS
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://link.com)` 
            HTML: `<a href="https://link.com">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2023-12-07 18:15 UTC, kvramyasri7 requested changes

2023-12-07 18:15 UTC, kvramyasri7 commented on src/fragments/lib/troubleshooting/common/upgrading.mdx
> +## 1. Upgrade your dev environment
super nit
```suggestion
## 1. Please update your dev environment
```

2023-12-07 18:15 UTC, kvramyasri7 commented on src/fragments/lib/troubleshooting/common/upgrading.mdx
> +## 2. Upgrade your Amplify project dependencies
super nit:
```suggestion
## 2. Please update your Amplify project dependencies
```

2023-12-07 18:15 UTC, kvramyasri7 commented on src/fragments/lib/troubleshooting/common/upgrading.mdx
> +## 3. Upgrade Amplify CLI version and configuration file
super nit: 
```suggestion
## 3. Please update Amplify CLI version and configuration file
```

2023-12-07 18:15 UTC, kvramyasri7 commented on src/fragments/lib/troubleshooting/common/upgrading.mdx
> +## 4. Upgrade category usage
super nit:
```suggestion
## 4. Please update category usage
```

2023-12-07 18:15 UTC, kvramyasri7 commented on src/fragments/lib/troubleshooting/common/upgrading.mdx
> +### In App Messaging
```suggestion
### In-App Messaging
```

2023-12-07 18:15 UTC, kvramyasri7 commented on src/fragments/lib/troubleshooting/common/upgrading.mdx
> +DataStore is no longer supported in an SSR context: if you are using DataStore within your SSR project, you will need to migrate to the API category.
Suggestion: some thing like that. Please add a link to API category as well 🙏🏼
```suggestion
We no longer support DataStore in SSR context: Please make sure to migrate to API category 
```

2023-12-07 18:39 UTC, kvramyasri7 commented
But why update in PR title and upgrade elsewhere?

2023-12-07 19:12 UTC, nadetastic submitted a review, later dismissed

2023-12-08 18:33 UTC, cwomack approved these changes

2023-12-08 18:57 UTC, cwomack approved these changes

2023-12-08 18:59 UTC, nadetastic approved these changes

2023-12-08 19:00 UTC, merged