fix: add domainPrefix to example of social provider
aws-amplify/docs pull request #6780
Opened 2024-01-14 15:11 UTC by fossamagna

#### Description of changes:

adds `domainPrefix` in example code when use of sign-in with social providers.
The `domainPrefix` is value added at https://github.com/aws-amplify/amplify-backend/pull/856.

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] Swift
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [x] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-01-16 16:18 UTC, josefaidt commented on src/pages/gen2/build-a-backend/auth/add-social-provider/index.mdx
> +You also need to configure your `domainPrefix` for your user pool domain, which will be OAuth redirect URI.
```suggestion
The following is an example of how you would set up access to all of the social providers supported by Amplify Auth. Please note you will need to configure your `callbackUrls` and `logoutUrls` URLs for your application, which will inform your backend resources how to behave when initiating sign in and sign out operations in your app. You will also need to configure your `domainPrefix` for your user pool domain, which will be the redirect URI for your OAuth provider.
```

small adjustment to work around "you also need to configure..."

2024-01-16 16:18 UTC, josefaidt requested changes
Hey @fossamagna :wave: thank you for taking the time to file this! I've left one small suggestion to tweak some of the language, but overall it looks good! :rocket:

2024-01-16 23:48 UTC, fossamagna commented
@josefaidt Thank you for your suggestion. It was really helpful.

2024-01-17 00:55 UTC, josefaidt approved these changes

2024-02-13 00:17 UTC, fossamagna commented
@renebrandel @dbanksdesign  Is this RP has blockers? Is there anything I can do to get my PR reviewed?
Thanks.

2024-02-13 16:59 UTC, renebrandel approved these changes

2024-02-13 17:00 UTC, renebrandel commented
@fossamagna - thanks for your contribution. Approved and auto-merge enabled now.

2024-02-13 17:28 UTC, merged