custom examples
aws-amplify/docs pull request #6979
Opened 2024-02-29 05:02 UTC by ykethan

#### Description of changes:

adds cdk examples for Geo, Analytics, REST API, In-App messaging

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] Swift
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [x] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [x] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-03-01 00:42 UTC, josefaidt commented on src/directory/directory.mjs
> +                  path: 'src/pages/gen2/build-a-backend/add-aws-services/restapi/index.mdx'
can this be `rest-api`?

2024-03-01 00:46 UTC, josefaidt commented on src/pages/gen2/build-a-backend/add-aws-services/analytics/index.mdx
> +Amplify enables you to collect analytics data for your App. The Analytics category uses Amazon Cognito Identity pools to identify users in your App. Cognito allows you to receive data from authentica
the capitalization of "App" stands out. Should this be just "app" to align with the quickstart language? 
![image](https://github.com/aws-amplify/docs/assets/5033303/ca98e9eb-c1a0-4005-85a3-84731252f01d)

2024-03-01 00:47 UTC, josefaidt commented on src/pages/gen2/build-a-backend/add-aws-services/analytics/index.mdx
> +Amplify enables you to collect analytics data for your App. The Analytics category uses Amazon Cognito Identity pools to identify users in your App. Cognito allows you to receive data from authentica
```suggestion
Amplify enables you to collect analytics data for your app. The Analytics category uses Amazon Cognito Identity pools to _identify_ users in your app. Cognito allows you to receive data from authenticated and unauthenticated users in your app. 
```

2024-03-01 00:48 UTC, josefaidt commented on src/pages/gen2/build-a-backend/add-aws-services/analytics/index.mdx
> +We can use AWS CDK to create the necessary resources for analytics.
```suggestion
We can use [AWS Cloud Development Kit (AWS CDK)](https://docs.aws.amazon.com/cdk/latest/guide/home.html) to create the necessary resources for analytics.
```

2024-03-01 00:50 UTC, josefaidt commented on src/pages/gen2/build-a-backend/add-aws-services/analytics/index.mdx
> +
```suggestion

// create an IAM policy to allow interacting with Pinpoint
```

2024-03-01 00:50 UTC, josefaidt commented on src/pages/gen2/build-a-backend/add-aws-services/analytics/index.mdx
> +
```suggestion

// apply the policy to the authenticated and unauthenticated roles
```

2024-03-01 00:51 UTC, josefaidt commented on src/pages/gen2/build-a-backend/add-aws-services/analytics/index.mdx
> +
```suggestion

// patch the custom Pinpoint resource to the expected output configuration
```

2024-03-04 20:43 UTC, josefaidt requested changes

2024-03-05 18:54 UTC, josefaidt commented on src/pages/gen2/build-a-backend/add-aws-services/rest-api/index.mdx
> +export const handler: APIGatewayProxyHandlerV2 = async (event) => {
```suggestion
import type { APIGatewayProxyHandlerV2 } from "aws-lambda";

export const handler: APIGatewayProxyHandlerV2 = async (event) => {
```

2024-03-05 19:00 UTC, josefaidt submitted a review, later dismissed

2024-03-07 16:01 UTC, josefaidt approved these changes

2024-03-07 20:49 UTC, Amplifiyer approved these changes

2024-03-07 21:44 UTC, katiegoines approved these changes

2024-03-07 22:19 UTC, merged