Custom subscription docs to Gen 2
aws-amplify/docs pull request #7120
Opened 2024-03-25 20:50 UTC by renebrandel

#### Description of changes:
- Gen 2 docs for custom subscriptions

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] Swift
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-03-25 21:37 UTC, iartemiev commented on src/pages/gen2/build-a-backend/data/custom-subscription/index.mdx
> +  }
`payload` isn't needed here
```suggestion
  return {}
```

2024-03-25 21:42 UTC, iartemiev requested changes
Looks good, other than the redundant `payload: null`

2024-03-25 23:53 UTC, josefaidt approved these changes

2024-03-26 09:56 UTC, iartemiev approved these changes

2024-03-26 14:00 UTC, merged