fix: add missing command in backend app setup
aws-amplify/docs pull request #7236
Opened 2024-04-17 22:18 UTC by reesscot

Changing into the backend-app folder wasn't included in the command

#### Description of changes:

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] Swift
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-04-17 22:19 UTC, reesscot commented on src/pages/[platform]/deploy-and-host/fullstack-branching/mono-and-multi-repos/index.mdx
> +1. Run `mkdir backend-app && cd backend-app && npm create amplify@beta` to set up a backend-only Amplify project. Commit the code to a Git provider of your choice.
Does this even make sense? We prompt you where you want to create the project, so we could just drop `mkdir backend-app` entirely:

```suggestion
1. Run `npm create amplify@beta` to set up a backend-only Amplify project. Commit the code to a Git provider of your choice.
```

2024-04-17 22:20 UTC, reesscot commented on src/pages/[platform]/deploy-and-host/fullstack-branching/mono-and-multi-repos/index.mdx
> +1. Run `mkdir backend-app && cd backend-app && npm create amplify@beta` to set up a backend-only Amplify project. Commit the code to a Git provider of your choice.
![CleanShot 2024-04-17 at 15 20 23](https://github.com/aws-amplify/docs/assets/6165315/07d8aacc-2897-4a13-9514-11f11b394baa)

2024-05-03 23:20 UTC, katiegoines approved these changes

2024-05-03 23:27 UTC, jacoblogan approved these changes

2024-05-03 23:50 UTC, renebrandel requested changes
Nope. This is intended.

2024-05-04 03:17 UTC, closed without merging