Add mobile storage docs
aws-amplify/docs pull request #7314
Opened 2024-04-25 18:53 UTC by hdworld11

#### Description of changes:

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] Swift
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-04-25 18:58 UTC, aspittel submitted a review, later dismissed

2024-04-25 19:44 UTC, phantumcode approved these changes

2024-04-26 00:37 UTC, aspittel approved these changes

2024-04-26 15:56 UTC, aspittel approved these changes

2024-04-26 16:00 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/list-files/index.mdx
> +### More `list` options
This is an anti-pattern. It's kinda fo the same as "advanced workflows" in the end it doesn't really mean anything. The table below can have their won headings:

"### List app files under the specified path"

"### Paginate through files under a specified path"

"### Use with S3 Transfer Acceleration"

2024-04-26 16:01 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/authorization/index.mdx
> +To grant all guest (i.e. not signed in) users of your application read access to files that start with `folder/*`, use the following `access` values.
make the example more realistic like:

```
`publicly-accessible/*`
```

2024-04-26 16:03 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/authorization/index.mdx
> +A user with identity id "documents" would be able to perform read/write/delete operations on files within `folder/documents/*` and would not be able to perform actions on files with any other prefix.
I don't undersstand this. The word "identity ID" and and "entity id" seems to be intermixed. What would a "identity id" of "documents" mean? Isn't this always a user sub?

2024-04-26 16:04 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/authorization/index.mdx
>        allow.entity('identity').to(['read', 'write', 'delete'])
what other "entity"s are allowed here

2024-04-26 16:04 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/authorization/index.mdx
>        allow.entity('identity').to(['read', 'write', 'delete'])
what "qualifies" as an entity?

2024-04-26 16:06 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/authorization/index.mdx
>  ### Prefix behavior
I don't have a good alternative. But this has actually less to do with the prefix behavior and more to do with the authorization rules' evaluation order

2024-04-26 16:07 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/copy-files/index.mdx
>  Cross identity ID copying is only allowed if the source object's access level is set to 'protected'.
I thought we don't have the concept of "access level" anymore

2024-04-26 16:07 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/copy-files/index.mdx
> +### More `copy` options
Same feedback as above. You can collapse this under one heading of "Use with S3 Transfer Acceleration"

2024-04-26 16:10 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/define-storage/index.mdx
> +Note that because the storage category requires auth, you will need to either configure [guest access](/[platform]/build-a-backend/auth/enable-guest-access/) or [sign in a user](/[platform]/build-a-b
I thought we support both of these now by default, do we still need this?

2024-04-26 16:12 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
> +### More `getUrl` options
same feedback as before.

2024-04-26 16:13 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
> +## API to download to file
as a file?

2024-04-26 16:13 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
> +## API to download to file
as raw data?

2024-04-26 16:13 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
> +| pluginOptions | Extra plugin specific options, only used in special circumstances when the existing options do not provide a way to utilize the underlying storage system's functionality. |
like what?

2024-04-26 16:15 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
> +### Query transfers
Maybe "Query for ongoing transfers"?

2024-04-26 16:15 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/remove-files/index.mdx
> +</InlineFilter>
same question here. I'm not sure exactly what pluginOptions gives me

2024-04-26 16:16 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx
> +<Block name = "Mobile & Desktop">
will this work? I think the " = " need to be removed

2024-04-26 16:17 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx
> +### Monitor upload progress
I think above I had "Query ongoing transfers". Maybe that should actually be changed to "Monitor ongoing transfers"? How is this different than that other heading in Android?

2024-04-26 16:18 UTC, renebrandel commented on src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx
> +### Transfer with Object Metadata
what is object metadata?

2024-04-26 16:19 UTC, renebrandel requested changes
Overall the code samples are exhaustive.
Main issue: "entity" part of the authorization isn't clear. I'm not sure the example actually matches the use case.

Nit: some of the headings didn't strike me as important.

2024-04-26 19:38 UTC, renebrandel approved these changes

2024-04-26 19:39 UTC, aspittel approved these changes

2024-04-26 19:41 UTC, merged