update gen2 auth set up
aws-amplify/docs pull request #7357
Opened 2024-04-30 00:23 UTC by josefaidt

#### Description of changes:

split off from https://github.com/aws-amplify/docs/pull/7312 for ease of review
next steps pages pointing to `/concepts` in a follow-up pr

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] Swift
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-04-30 13:07 UTC, ykethan approved these changes

2024-04-30 20:43 UTC, arundna commented on src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
> +npx amplify sandbox
```suggestion
npx ampx sandbox
```

2024-04-30 20:43 UTC, arundna commented on src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
>  npx amplify sandbox --config-format dart --config-out-dir lib
```suggestion
npx ampx sandbox --config-format dart --config-out-dir lib
```

2024-04-30 20:43 UTC, arundna commented on src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
> +npx amplify sandbox --config-out-dir app/src/main/res/raw
```suggestion
npx ampx sandbox --config-out-dir app/src/main/res/raw
```

2024-04-30 20:43 UTC, arundna commented on src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
> +npx amplify sandbox
```suggestion
npx ampx sandbox
```

2024-04-30 20:55 UTC, chrisbonifacio requested changes

2024-04-30 20:55 UTC, chrisbonifacio commented on src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
>  After a successful deployment, this command also generates a configuration file (`amplifyconfiguration.json`) to enable your frontend app to connect to your backend resources. The values you configur
```suggestion
After a successful deployment, this command also generates a configuration file (`amplify_outputs.json`) to enable your frontend app to connect to your backend resources. The values you configure in your backend authentication resource are set in the generated configuration file to automatically configure the frontend [`Authenticator connected component`](https://ui.docs.amplify.aws/react/connected-components/authenticator).
```

2024-04-30 20:55 UTC, chrisbonifacio commented on src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
>  import config from '@/amplifyconfiguration.json';
```suggestion
import config from '@/amplify_outputs.json';
```

2024-05-01 22:26 UTC, reesscot approved these changes

2024-05-01 22:37 UTC, arundna approved these changes

2024-05-01 22:55 UTC, merged