chore(flutter): Gen 2 Storage Banner
aws-amplify/docs pull request #7381
Opened 2024-04-30 19:28 UTC by Equartey

#### Description of changes:
Adds a banner to Gen 2 Storage pages for Flutter.

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [x] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] Swift
- [ ] Android
- [x] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [x] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [x] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

### When this PR is ready to merge, please check the box below
- [x] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-04-30 19:52 UTC, swaminator requested changes

2024-04-30 19:52 UTC, swaminator commented on src/pages/[platform]/build-a-backend/storage/authorization/index.mdx
> +  fragments={{ flutter: flutter0 }}
We are not using Fragments anymore and have switched to `<InlineFilter>`. can you please update?

2024-04-30 19:52 UTC, swaminator commented on src/fragments/lib/storage/flutter/gen2-banner.mdx
> +Gen 2 storage support will be available in the next major version of Amplify Flutter.
New storage functionality available in Gen 2 (e.g. custom paths) is not yet available for Flutter.

2024-04-30 21:54 UTC, khatruong2009 approved these changes

2024-05-01 19:11 UTC, swaminator submitted a review, later dismissed

2024-05-01 19:14 UTC, swaminator approved these changes

2024-05-01 19:16 UTC, Jordan-Nelson approved these changes

2024-05-01 19:17 UTC, reesscot approved these changes

2024-05-01 19:20 UTC, merged