Adds instruction to invoke a function via its url
aws-amplify/docs pull request #7595
Opened 2024-05-15 15:39 UTC by johnpc

#### Description of changes:

This PR updates the [Set up a Function](http://docs.amplify.aws/react/build-a-backend/functions/set-up-function/#pageMain) page to include instructions on how to to invoke the function you've created via a function url.

We may prefer to edit this to put the function behind the data schema instead, but this option works. It also fixes the existing type issue in https://github.com/aws-amplify/docs/issues/7594 because it is able to type the function event as a `LambdaFunctionURLEvent`.

#### Related GitHub issue #, if available:

Fixes https://github.com/aws-amplify/docs/issues/7594

#### Checks

- [x] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [x] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [x] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [x] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [x] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-05-16 18:41 UTC, jacoblogan approved these changes

2024-05-20 16:31 UTC, renebrandel requested changes
this shouldn't be the "primary flow", as it'll likely result in a few unexpected situations for the customer. There's no authZ protection, e2e type safety, and customers need to think about "CORS". 

I think we should this "Enable function URLs" as a separate with a callout that we don't recommend this directly.

2024-05-20 16:31 UTC, renebrandel commented
Instead the default flow, should go through data.

2024-06-28 20:48 UTC, josefaidt commented
Closing this in favor of the data approach with https://github.com/aws-amplify/docs/pull/7759

2024-06-28 20:48 UTC, closed without merging