Updated Amplify doc to add sdk v3 code
aws-amplify/docs pull request #7674
Opened 2024-05-29 15:17 UTC by meghasv09

#### Description of changes:

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] Swift
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-06-07 21:46 UTC, josefaidt commented on src/pages/gen1/[platform]/build-a-backend/functions/secrets/index.mdx
> +const {ssm} = require("@aws-sdk/client-ssm");
can we pivot this example to use the SSMClient from this package and the GetParametersCommand? 

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm/
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm/command/GetParametersCommand/

2024-06-07 21:46 UTC, josefaidt requested changes
Hey @meghasv09 :wave: thanks for taking the time to file this! Left a small comment, but overall we appreciate your contribution!

2024-06-10 15:12 UTC, josefaidt approved these changes

2024-06-10 18:22 UTC, timngyn approved these changes

2024-06-10 18:42 UTC, merged