fix(js): Add 1.1.x version for js React Native v5 push notification
aws-amplify/docs pull request #7689
Opened 2024-05-31 22:22 UTC by yuhengshs

#### Description of changes:

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [x] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [x] JS
- [ ] Swift
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [x] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [x] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [x] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-06-02 21:15 UTC, renebrandel requested changes
Nit on wording.

2024-06-02 21:15 UTC, renebrandel commented on src/fragments/lib-v1/push-notifications/react-native/getting_started/40_install_lib.mdx
> +    Please note that v5 is compatible only with @aws-amplify/rtn-push-notification version 1.1.x
```suggestion
Note: Amplify JavaScript v5 is only compatible with @aws-amplify/rtn-push-notification version 1.1.x
```

2024-06-03 17:20 UTC, cshfang approved these changes

2024-06-03 17:40 UTC, renebrandel approved these changes

2024-06-05 17:16 UTC, hdworld11 approved these changes

2024-06-05 17:16 UTC, merged