Added an example page for setting up custom-auth-flows
aws-amplify/docs pull request #7947
Opened 2024-09-06 19:04 UTC by yuhengshs

#### Description of changes:

#### Related GitHub issue #, if available:

### Instructions

**If this PR should not be merged upon approval for any reason, please submit as a DRAFT**

Which product(s) are affected by this PR (if applicable)?
- [ ] amplify-cli
- [ ] amplify-ui
- [ ] amplify-studio
- [ ] amplify-hosting
- [ ] amplify-libraries

Which platform(s) are affected by this PR (if applicable)?
- [ ] JS
- [ ] Swift
- [ ] Android
- [ ] Flutter
- [ ] React Native

**Please add the product(s)/platform(s) affected to the PR title**

#### Checks

- [ ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?

- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?

- [ ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
      _ref: MDX: `[link](https://docs.amplify.aws/)` 
            HTML: `<a href="https://docs.amplify.aws/">link</a>`_

### When this PR is ready to merge, please check the box below
- [ ] Ready to merge

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-09-06 21:26 UTC, josefaidt commented on src/pages/[platform]/build-a-backend/functions/examples/custom-auth-flows/index.mdx
> +    'Leverage Custom Auth with and without SRP, Allowing for a series of challenge and response cycles that can be customized to meet different requirements during sign in.',
```suggestion
    'Leverage Custom Auth with and without SRP, allowing for a series of challenge and response cycles that can be customized to meet different requirements during sign in.',
```

2024-09-06 21:28 UTC, josefaidt commented on src/pages/[platform]/build-a-backend/functions/examples/custom-auth-flows/index.mdx
> +    event.response.issueTokens = false;
for folks seeing this trigger for the first time it's tough to grok what each of these steps mean or are doing, can we add a short comment like "verify password challenge" inside each of the conditional blocks?

2024-09-06 21:29 UTC, josefaidt commented on src/pages/[platform]/build-a-backend/functions/examples/custom-auth-flows/index.mdx
> +After deploying the changes, whenever a user attempts to sign in with `CUSTOM_WITH_SRP` or `CUSTOM_WITHOUT_SRP`, the lambda challenges will be triggered.
```suggestion
After deploying the changes, whenever a user attempts to sign in with `CUSTOM_WITH_SRP` or `CUSTOM_WITHOUT_SRP`, the Lambda challenges will be triggered.
```

2024-09-06 21:30 UTC, josefaidt requested changes
Hey @yuhengshs I like these examples, thank you for taking the time to file this! I left a few small comments, but can we also add a callout/link to this page from https://docs.amplify.aws/react/build-a-backend/auth/connect-your-frontend/switching-authentication-flows/#custom_with_srp--custom_without_srp-flows ?

2024-09-09 17:48 UTC, josefaidt commented on src/pages/[platform]/build-a-backend/auth/connect-your-frontend/switching-authentication-flows/index.mdx
> +
```suggestion

To create a CUSTOM_AUTH challenge with a Lambda Trigger, please visit [AWS Amplify Custom Auth Challenge example](/[platform]/build-a-backend/functions/examples/custom-auth-flows/) for setup instructions. 
```

2024-09-09 17:51 UTC, josefaidt approved these changes

2024-09-10 23:26 UTC, josefaidt approved these changes

2024-09-11 15:50 UTC, cwomack approved these changes

2024-09-11 16:36 UTC, jacoblogan approved these changes

2024-09-12 16:00 UTC, aspittel approved these changes

2024-09-12 17:24 UTC, josefaidt approved these changes

2024-09-12 17:26 UTC, merged